### ISSUE TITLE
ENgetcoord function broken

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#10]
Discussion welcome: should the library load coordinates? is that the job of the engine? or should we break of the .inp file parser into a separate utility?

**Comment by eldemet** [comment]
@samhatchett For some applications it is usefult if the toolkit returns the coordinates. For instance when developing a new GUI, or when conducting some spatio-temporal analysis which uses local coordinates for proximity measures etc. In the case of the EPANET Matlab toolkit, we are reading the INP file and manually return the coordinates, however this is not efficient. Also, we may want to have the ability of adding/removing nodes in the network through the toolkit; this would also allow for some new types of analysis.

**Comment by eladsal** [comment]
It's not the job of the engine but it's the job of the Toolkit so in my opinion it should be included. Coordinates and vertices are used in many applications (see the latest [R-EpanetReader](https://github.com/bradleyjeck/epanetReader) which has a plot function).

The default behavior should be that coordinates are not loaded but it would be good to have some kind of function like `ENopenwithcoords` which would set a global variable (`LoadCoordinates`) to true and then call `ENopen`.

**Comment by eladsal** [comment]
In the `coordinates-getter` branch I have fixed the [ENgetcoord](https://github.com/OpenWaterAnalytics/EPANET/blob/coordinates-getter/src/epanet.c#L1282) function. Basically I had to rewrite the thing since the previous code try to imitate the curves code which is totally different. Please test in your environments.

The straightforward way to add coordinates is probably to add X and Y variables to the Node structure but this might increase memory use when no coordinates are needed to be loaded - do you think it's important?. Instead I used a separate structure which could be initialized only if needed. I also added a flag to show when there are no coordinates for a specific node and I don't set a default values for missing coordinates.

It's not difficult to add the `ENsetcoord` function but there is some work on saving the coordinates section which is not there at the moment.

Currently the coordinates are loaded and there is no way for the user to control that. Need to discuss the best way to do it.

**Comment by samhatchett** [comment]
great - i think if this works intuitively then it is a valuable addition. i'm fine with ignoring the .inp file output portion for now since all that is likely to undergo major surgery anyway.

**Comment by eladsal** [comment]
Added a flag which controls the loading of coordinates at epanet.c [line 213](https://github.com/OpenWaterAnalytics/EPANET/blob/coordinates-getter/src/epanet.c#L213). Currently this flag can't be changed by the user (hard coded).

When set to TRUE coordinates are loaded and users can use the `ENgetcoord` and `ENsetcoord` functions. Changes are then saved when `ENsaveinpfile` is called.

When set to FALSE coordinates are not loaded and can't be retrieved or changed. When saved, the `[COORDINATES]` section is copied from the original INP file. Also, when set to FALSE no memory allocation is made for the coordinates structure.

Please test the functions on your platforms before I make a pull request.
