### ISSUE TITLE
Default values for links in AddLink

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#102]
Some link properties are mandatory and can't be set to zero according to it's type (length, diameter, roughness).

We can have these properties passed in the function call since they will have to be set anyway. As a temporary workaround I'll add default values.

**Comment by AbelHeinsbroek** [comment]
Those properties are only mandatory for pipes, not for valves and pumps. Do you propose splitting the ENaddlink to ENaddpipe, ENaddvalve and ENaddpump functions?

**Comment by eladsal** [comment]
Well, diameter is also mandatory for valves :)

I wasn't thinking of separate functions but that is not such a bad idea (also for nodes). I'm testing the net builder functions and to build a network you have to input all the properties so why not have separate functions with the ability to pass *all* the properties, not only the mandatory ones? At the moment, when adding a tank, not only that you have to make one function call for each property, but you also have to do it in the right order (for example: you can't set the minimum level before the maximum level and so on...). I think this would be also easier to maintain and debug but the list of parameters would be loooong.

So yes, I'm now proposing to split the `ENaddlink` and `ENaddnod`e functions - what do you think?

**Comment by samhatchett** [comment]
Default values make sense, thanks @eladsal 

In regard to the _many_ calls that would be required to set all the proper parameters in the right order, what about modifying the `add` functions to accept [variadic arguments](http://www.gnu.org/software/libc/manual/html_node/Variadic-Example.html#Variadic-Example):

```
int DLLEXPORT EN_addnode(EN_Project *p, char *id, EN_NodeType nodeType, ...)
```

and specify the required parameters as additional arguments, which will then be read in the `va_list` - with any misuse returning an error. This is a sort of functional overloading that is allowed in C, and would do the job. Given this, the options become:

- use `add` function, then use each setter in the right order (many calls)
- declare separate `add` functions for each node/link type (many functions)
- use variadic `add` (more documentation needed for proper use)

**Comment by eladsal** [comment]
> declare separate add functions for each node/link type (many functions)
To me this option makes a lot of sense. Currently we have 3 node types and 3 link types each with slightly different properties and with some shared ones (for links\nodes). These functions should have at minimum the mandatory properties. We still can have inner functions for `addNode` and `addLink` which will be called from the 6 add functions.

**Comment by samhatchett** [comment]
I like it @eladsal 

so a total of 8 functions? one for each element type (junction,tank,reservoir,pipe,pump,valve) and `addnode` / `addlink` functions which set default values.

one other thought would be to return-by-reference the resulting element Index so that subsequent setter calls can use that without having to look it up. like:

```
EN_addnode(EN_Project *p, char *id, EN_NodeType nodeType, int* newIndex)
```

**Comment by eladsal** [comment]
`newIndex` is a good suggestion.

What I had in mind is that the `addNode` and `addLink` functions would be inner ones which are called from the other six functions.

**Comment by AbelHeinsbroek** [comment]
I agree with the addition of newIndex to the `addNode` and `addLink` functions, with the condition that those two functions are private and not accessible through the API. 

The only public facing methods would then be `EN_addpipe`, `EN_addjunction` etc.

**Comment by eladsal** [comment]
The `EN_addpipe`, `EN_addjunction`... can return the `newIndex` as well.

**Comment by AbelHeinsbroek** [comment]
Sure they can, but I would strongly recommend against it. 

As earlier stated the index is no longer consistent for objects. Returning the newindex is in my opinion of little use as we've already set all the necessary parameters (length, diameter, etc.) in the function call. 
Furthermore, it can and will lead to frustration and unexpected and unintuitive problems for the toolkit users not as familiar with the source code. For example, they may be inclined to store the newIndex values returned in a list to use later in the program to request values or make further changes. Because the indices change they end up requesting the wrong values or changing the wrong objects.

**Comment by eladsal** [comment]
@AbelHeinsbroek I understand and incline to agree. Thanks!

**Comment by eladsal** [comment]
Moving to 2.3
