### ISSUE TITLE
Add SWIG interface generators

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#110]
requires some special handling for opaque pointers:
https://github.com/swig/swig/wiki/FAQ#q-how-do-i-interact-with-functions-that-require-double-void-pointers---void-

... but will let us do python-based testing more easily and also build better downstream python abstractions with less complicated dependencies.

**Comment by michaeltryby** [comment]
I discovered [SWIG typemaps for Numpy](https://docs.scipy.org/doc/numpy/reference/swig.interface-file.html). They might turnout to be helpful for this issue.

**Comment by michaeltryby** [comment]
@samhatchett I was thinking about going ahead and SWIG wrapping the Toolkit API. Any thoughts on where these changes should live? :stuck_out_tongue_winking_eye: 

I have heard no response from @mauriziocingi on placing packages over at [epanet-python](https://github.com/OpenWaterAnalytics/epanet-python).

**Comment by mauriziocingi** [comment]
Hi, sorry for late reply...
Just two points:
1) swig makes only a bridge between C and Python, it does not create a true
pythonic code. Hand made interface can be much more tailored on Python
style. Otherwise "something is better than nothing"
2) in epanet/python repository I've already included a python module
"outbin" that reads epanet binary files without any c code.(but I'm not
sure, maybe I wrote it but not yet published.)

Another point: we have to consider that binary out file isn't a good place
for upload variables. Remember that in outbinfiles you can read values at
report_timestep intervals. If something changes in the between (i.e. rules
triggered, tanks empty or full etc.) nothing will be reported. I can send
an example with a pump switching on/off very offen but reported always off
in binary output and epanet graph (a small article but unfortunatly in
italian....). For this reason I always recomend a cycle of hydraulic
solving over timestep and get/report of every important value...

Maurizio


Il 06 Nov 2017 20:06, "Michael Tryby" <notifications@github.com> ha scritto:

@samhatchett <https://github.com/samhatchett> I was thinking about going
ahead and SWIG wrapping the Toolkit API. Any thoughts on where these
changes should live? 😜

I have heard no response from @mauriziocingi
<https://github.com/mauriziocingi> on placing packages over at epanet-python
<https://github.com/OpenWaterAnalytics/epanet-python>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OpenWaterAnalytics/EPANET/issues/110#issuecomment-342251939>,
or mute the thread

**Comment by michaeltryby** [comment]
@mauriziocingi I 100% agree with you. SWIG generates a "bridge" between C and python and that bridge is not always as pythonic as we would like. Our thought is that we can automate creation of the bridge using SWIG and then concentrate our efforts building pythonic packages on top. 

One way you can contribute is by thinking about a pythonic EPANET and building it on top of the SWIG generated packages I am setting up. Lots of opportunity here for you to create exactly what you want. How does that sound?  

The [python packages](https://github.com/OpenWaterAnalytics/EPANET/tree/feature-nrtest/tools) I've developed for EPANET need a home. Would you be willing to provide one in your epanet-python repo? 

I also agree with you on the problems with EPANET report files, but that seems like another issue.

**Comment by michaeltryby** [comment]
@samhatchett I'm getting in to the SWIG toolkit wrapper. And I have a question for you. 

Is there a reason why the `EN_epanet()` call in the new threadsafe API doesn't have a pointer to `EN_Project` as an argument?

**Comment by eladsal** [comment]
If I'm not mistaken there is no need for `EN_Project` in `EN_epanet` since it opens the INP file, runs the entire simulation and closes everything.

**Comment by samhatchett** [comment]
@eladsal is correct - but @michaeltryby, can you show me where is this function `EN_epanet(...)`? I can't find it. I do see `ENepanet(...)` - which is in the "legacy" api.

**Comment by michaeltryby** [comment]
There is a declaration for it in feature-wrapper/[epanet2.h](https://github.com/OpenWaterAnalytics/EPANET/blob/feature-wrapper/include/epanet2.h) line 1122

**Comment by samhatchett** [comment]
that is a mistake - the function is not implemented, and it would be duplicative to do so. agreed?

**Comment by michaeltryby** [comment]
Yep I agree.

**Comment by michaeltryby** [comment]
Building the Swig wrapper is going to be tricky. I have been experimenting with scikit-build and it doesn’t support swig very well at al. While cmake does provide support for swig it doesn’t integrate with scikit-builds python packaging capabilities very well at al. Making it inferior to Python’s setup tools in this respect. Disappointing to say the least.

**Comment by michaeltryby** [comment]
I think the best solution maybe to build EPANET library using cmake and to build the swig wrapper using python setup and configure it to link in the library.

**Comment by bemcdonnell** [comment]
@michaeltryby, we can’t we build epanet / swmm as python extensions instead of link to a precompiled binary? I like how you’ve done the output api. From the python workflow, it seems to be the cleanest. But I suspect you have a reason - i just don’t know what it is.

**Comment by samhatchett** [comment]
Since Python seems to be the main goal, does anybody have an idea of how SIP might work here? I just haven’t been able to look that closely at it yet, but I’ve got the impression that this might be a good application for it.

**Comment by michaeltryby** [comment]
I'm making progress on swig wrapping the toolkit API. I need an api function to free memory. We already have int EN_free(EN_ProjectHandle *ph) but it would be nice to have void EN_free(void **array)

Anybody have a preference on how to resolve this?

**Comment by michaeltryby** [comment]
@samhatchett any thoughts?
