### ISSUE TITLE
avoid negative pressure results

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#163]
should we make this a halting condition?

**Comment by shenh** [comment]
Negative pressures can reveal wrong junction elevation inputs, and therefore are useful to review the model. It makes more sense to allow the program to complete to me.

**Comment by samhatchett** [comment]
Thanks. @lrossman noted this item in context of needed improvements to EPANET. Hopefully he can help illuminate the various connotations.

**Comment by michaeltryby** [comment]
@shenh I think the issue is that solutions provided by EPANET with large negative pressures are not physically realistic. EPANET assumes that demands are independent of pressure and always satisfied. Thus it is possible for large negative pressures to develop in the solution. It is more realistic to assume that demands are pressure dependent and when pressure is insufficient to meet demands, demands will decrease. Resulting in a very different network solution that perhaps will be more useful for design and analysis of distribution systems.

**Comment by shenh** [comment]
@michaeltryby I totally agree pressure dependent demand is more realistic for certain scenarios such as pipe break, building sprinkler. Demand is pressure dependent in nature in such scenarios. I do hope this feature can be added to the future EPANET engine. 

Pulling a fixed demand as EPANET is currently doing may also provide useful information even if may cause negative pressure. For example for development type analysis municipalities would need to analyze what is the existing system response to supply a proposed development (eg 5 L/s). If negative pressures in the vicinity happen, more booster pumps may be needed to open to increase the pressure. Negative pressures do provide useful info sometimes.
