### ISSUE TITLE
Time for Coding Standards?

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#179]
I just had my first look into the dev branch of EPANET where I guess the next "near-term" version of open source EPANET will emerge from. I am somewhat concerned that the code, which in the past people complained was not that easy to work with (although I never had a problem - LOL), is becoming even more obtuse. The decision to make the API thread safe has added a new layer of complexity to almost every function. The lack of a consistent formatting style and naming convention is not helping, nor is the decision to keep adding more and more code into the existing files instead of breaking them into smaller, more coherent modules.

Does anyone else think it's time to adopt some coding standards (e.g., naming conventions, indentation policy, curly brace policy, file size criteria, etc.) and use these to refactor the existing code to improve its consistency, readability and maintainability?

**Comment by michaeltryby** [comment]
@LRossman I think a lot of people have been hesitant to refactor EPANET in a major way for two reasons. One they are afraid of breaking it. And two, they are waiting for EPANET 3.0.  

I agree the code needs some work. Perhaps we can call a Dev Comm meeting and discuss this among other issues like nailing down the scope of the next release. Thoughts?

**Comment by jamesuber** [comment]
@LRossman I like @michaeltryby idea of having a meeting to discuss Epanet refactoring. This has been advocated by the dev comm for some time, and is still sorely needed. Those discussions are at the heart of this project. I am sure such a meeting would accommodate issues of coding standards. 

And the issue of "standards" can also be broadened, I think, to things like "should we allow dependencies within the Epanet engine code base?" Lew when you first designed Epanet, that same question was more or less the same as asking "should we require a user to buy the IMSL scientific libraries in order to use Epanet?" The world is different now, as we all know.

Getting back to refactoring. That discussion should begin with a question like "How do we want to use Epanet engine software -- what should it be able to do?" I don't think there has been a focused discussion and a clear answer to that question, from a software design perspective. (Please do correct me if I'm wrong, anyone.) For example, some ideas that I've heard in the past from dev comm members and others: 
- I want to instantiate multiple models in a thread safe manner
- I want to easily and reliably swap out core modules for nonlinear/linear system solution, EPS time integration, etc.
- I want Epanet to efficiently integrate with gradient based optimization software for parameter estimation
- I want Epanet to fully support building, running, and querying network models in software as the primary way to interact with the engine"

We really need to come to agreement on these sorts of design goals. Talking about Epanet 3 without doing that doesn't make very much sense, in my opinion, especially as an open source project.

Some of us will be in Minneapolis for the EWRI meeting in 1.5 weeks. Others can join by video. Should we set up a 2-3 hour meeting and get the logistics down for that? I will help.

**Comment by michaeltryby** [comment]
@LRossman if I understand you correctly, your vision for EPANET v2.2 is to backport some of the features developed over at epanet-dev addressing Issues #160 - #165. And generally cleaning up and improving the code along the way. Do I have that right? That's in line with my thinking on the subject. 

Or do you mean something different when you describe using epanet-dev as "the basis" for 2.2?

**Comment by LRossman** [comment]
@michaeltryby I mean to port essentially the entire C++ OOP structure behind epanet-dev, which I know is going to shake things up quite a bit. Just "rearranging the deck chairs" of EPANET 2 dev is like putting lipstick on a pig. There is so much to be gained by moving to C++ (the string class, the standard template library, exception handling). Plus the code is essentially good to go right now (at least my private development version - the version on epanet-dev is incomplete and out of date). I'll volunteer to port it over to the EPANET 2 repository as a new branch so people can check it out.

**Comment by samhatchett** [comment]
Lew, I’ve tried to figure out who should be offended by your “lipstick on a pig” language, but I just ended up feeling exhausted and sad on behalf of all the well-intentioned people who have contributed their time and resources to the project. Are the modifications for threadsafety pretty? No, but it works, and solves a problem we had. Likewise for the controls api, and the add/remove element functions, and others that I’m forgetting. It took a collective effort to communicate about prior versions’ shortcomings and plot a path forward. And so every line is precious because someone thought it was worth giving away. 

But. Please bear in mind that I completely agree with most of Lew’s comments above. The C implementation is needlessly hamstrung by the language feature-set. C++ is most definitely the future. So I find it difficult to justify sinking a whole lot of effort into rearchitecting this codebase given that reality. 

As a developer of commercial software, I must say that I’ve had to absolutely mangle epanet 2 to get it to do what we want. It just wasn’t designed with our use-case in mind. The new epanet-dev (3) code was not designed that way either. What if the next major version came out of a considered process of investigating what kinds of things people in industry want to do programmatically? With an interface-first approach? That would be an endeavor I could perhaps justify investing in. Jim is right that this architectural discussion is long overdue. I think I’ve been waiting for more people to start saying that, but it seems that the number of developers in this field is so vanishingly small. Or maybe we are all introverts. 

At this point, I’m ready to strip down the 2.2 milestone to something that’s releasable within the next 3 months, and move on to higher-level discussions about needs assessment, abstractions, and interface design. 

Anyone else on board with that?

**Comment by LRossman** [comment]
@samhatchett I think you misinterpreted my "pig" comment. I wasn't referring to the effforts of those who have worked in the past on the EPANET 2 code, but to any future work that tries to make the code look "prettier" without really addressing its structural shortcomings.

**Comment by eladsal** [comment]
My two cents are that it is always time for coding standards. However, we should remember that we don't have that many contributors so we really don't need to spend a lot of time on it right now. Defiantly don't go for anything automatic. If we could have a short list of standards it would be good. Something which may include: indentation, spaces (a=b or a = b), where to declare variables, use of brackets and a few more.

**Comment by bemcdonnell** [comment]
Checkout what was done for OWA-SWMM:

https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/pull/88 

We never merged this in.. but this uses the clang-format tool.  

You define your formatting here:

https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/develop/.clang-format

**Comment by michaeltryby** [comment]
This thread is all over the place.

**Comment by eladsal** [comment]
I'm lost, what is the proposal? to run an automatic formatting tool with "[Google style](http://google.github.io/styleguide/)" - which one? Is that for the entire repository or for future commits (or both)?

**Comment by michaeltryby** [comment]
@samhatchett said: 
> At this point, I’m ready to strip down the 2.2 milestone to something that’s releasable within the next 3 >months, and move on to higher-level discussions about needs assessment, abstractions, and interface >design.

>Anyone else on board with that?

**Comment by eladsal** [comment]
> @samhatchett said:
> 
> At this point, I’m ready to strip down the 2.2 milestone to something that’s releasable within the next 3 >months, and move on to higher-level discussions about needs assessment, abstractions, and interface >design.
> 
> Anyone else on board with that?

I'm on board, thanks.

**Comment by eladsal** [comment]
@LRossman currently we have a [list of issues](https://github.com/OpenWaterAnalytics/EPANET/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.2) tagged for v2.2. We need to revisit these and decided which one goes in.

**Comment by LRossman** [comment]
@eladsal Thank you. That helps a lot. Since I opened this thread I am going to close it with stating that the consensus is to not worry about coding standards until 2.2 is released and (shooting down my proposal) not to make any major structural changes to the code at this time. Organizing tasks, assigning people to them, and tracking progress can be the subject of a new thread.
