### ISSUE TITLE
Establishing EPANET reg testing benchmark on Linux 64 bit

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#184]
CI is currently configured to build EPANET using gcc on Linux with failing reg tests. We have not done the work to establish a proper reg testing benchmark there. 

Since the code is already building on Linux gcc this issue involves establishing a reg testing benchmark on Linux gcc 64 bit. Thoughts?

**Comment by samhatchett** [comment]
This makes no sense, to have separate benchmarks per-platform or per-compiler. What makes more sense to me is settling on a testing framework that does not depend on platform or compiler. Are the differences really that significant? do the tests report on those differences? What really is the motivation for having a platform-dependent numerically-frozen test?

**Comment by dbhart** [comment]
I think that a suite of results would be helpful. We (on WNTR) have been doing regression testing against results of simulations from a specific windows build of EPANET (the most recent from the EPA website), with tolerances based on acceptable differences due to platform variance. If there were a suite of results, that might give us an ability to create a “mean/std dev” approach to regression testing to get a set of baseline results which can be used to demonstrate equivalent performance on different platforms. It would be good to make sure the water network models used for regression testing fully sample all the different valve types, etc.
