### ISSUE TITLE
Confusion over using cmake/msbuild versus Makefile.bat for Visual Studio builds

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#185]
I am confused over whether contributors are supposed to use _cmake/msbuild_ (driven by the _CMakeLists.txt_ file in the root folder of the repo) or the _Makefile.bat_ script (in the _win_build/WinSDK_ folder) when testing their code changes using the MSVC compiler. Or does it not matter (e.g., one could even use the Visual Studio UI if they so desire). 

Some things I discovered about the current _CMakeLists_ file are:

1. You need _cmake_ v. 3.7.2 or higher to make it work with Visual Studio 2017 (the latest _cmake_ release is 3.11.2).
2. If you don't have the Boost libraries installed on your machine cmake will fail due to lines 44 and 45:
`add_subdirectory(tools/epanet-output)
add_subdirectory(tests)` 
3. It defaults to using the /MD compiler setting which means that MS runtime library _MSVCRT.dll_ has to be on a user's machine for EPANET to work. I suggest this be changed to /MT so that the static version of the library is linked into the executable (which is how EPANET 2.0 was always built).

While _Makefile.bat_ is configured to produce both 32-bit and 64-bit versions of the program in a single build, separate invocations of _cmake/msbuild_ are needed to produce both versions (the second one would append "Win64" to the name of the compiler generator (e.g., "Visual Studio 15 2017 Win64") and you have to work in a "x64 Native Tools Command Prompt" shell).

**Comment by samhatchett** [comment]
`Makefile.bat` is deprecated and will be removed. Unless I am mistaken - I know that @eladsal has been quite fond of it?

Thanks for reporting the issue of requiring Boost - that should only be the case for testing. We should probably break off the testing build from the main cmake file. Furthermore, the tests only use the Boost Unit Test Framework, which has an option to be header-only, so we could decide to grab that on-the-fly rather than include the entire Boost mothership. 

As for dynamic/static linking, the better cmake configurations i've seen provide a flag to specify which type of build you want -- e.g., 

```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_SHARED_LIBS=0 -DBUILD_SAMPLES=0 -DBUILD_TESTS=0 
```

**Comment by LRossman** [comment]
@eladsal I am using Visual Studio Community 2017 Version 15.2. And in the last sentence of your post above, I hope you meant to say "painless" instead of "painful" 😏

**Comment by eladsal** [comment]
I did mean painless, thanks. Now I can't get that MASH theme song out of my head. 

In my last go at it I used the 2010 community version, or the Express one which was a crazy 2.5GB just to compile EPANET. It is probably larger now...
