### ISSUE TITLE
EN_setreport returns an error for NODES and LINKS settings

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#211]
When calling `EN_setreport` with "NODES ALL" or any other combination (also for links) returns an error that the node or links wasn't found. Can't find what went wrong since this worked before.

Can someone please verify this error?

**Comment by LRossman** [comment]
I have verified the error. It is caused by the string holding the report command not terminated with a line feed` \n`. This results in `gettokens` never finding a terminating character when it tokenizes the command. It thus returns `MAXTOKS` tokens, most of which hold garbage.

I have fixed the problem in PR #303.
