### ISSUE TITLE
Establish contribution workflow guidelines

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#222]
I propose we establish some best practices on our contribution workflow, where the standard GitHub Flow (described [here](https://guides.github.com/introduction/flow/)) is favored. 

This has many advantages over the status quo with very little in the way of extra effort on the part of the contributing developer. Anyone care to weigh in?

**Comment by bemcdonnell** [comment]
@eladsal, I think it comes down to the type of contribution. Over at the SWMM project, we never push directly to the develop branch unless it is something insignificant. For example, if I am to bump the version number or clean comments in a readme, I might push directly to develop. On the flip side, if my contribution is technical, i make sure it’s inside a PR.  

A PR announces what you are doing so that everyone else is aware. If you push a technical/changed code to develop, in my opinion it seems non collaborative. Since everyone contributing feels a sense of ownership, as collaborators we all need to know what’s coming in. This applies to anyone with push repository permissions.

**Comment by michaeltryby** [comment]
@eladsal There is nothing unreasonable about the GitHub flow. It just take a little getting used to. I use it all the time for everything I do. The developers over at the OWA SWMM repo use it for everything they do. It's not a problem. When everyone follows the same process it helps the contribution workflow run smoothly. 

I agree with @bemcdonnell, it's about communicating with your fellow developers and documenting the development process. Having related commits grouped into PR's helps upstream as I work on understanding what has been done.

**Comment by eladsal** [comment]
Thanks. I hear you and I'm not sure what I can say about non collaborative and communicating with your fellow developers. We are such a small group (maybe 4 committers) and commits are just a few so I don't really understand the problem we are trying to solve here. Commits are usually taking care of a specific issue so it is usually easy to follow. I didn't say the the GitHub flow is not reasonable, just not for all cases.

**Comment by michaeltryby** [comment]
@eladsal Sure I agree that this is a small project. But even so, we have had more than a dozen developers make several hundred commits totaling thousands of changes made. 

This is the point of our disagreement. I believe that following the GitHub Flow is essential when there are more than two developers. We are well past the point where we could benefit from implementing it.

**Comment by michaeltryby** [comment]
I propose we take a vote.

**Comment by eladsal** [comment]
@michaeltryby  wow, 6 hours, that was fast.... is that how we come to a consensus? Go ahead.

**Comment by michaeltryby** [comment]
@eladsal I am proposing a vote. The vote hasn't been adopted. The thread is still open for discussion.
