### ISSUE TITLE
get Count for other element 

### ISSUE THREAD

**Issue by milad-ghiami** [OpenWaterAnalytics/EPANET#225]
Hi every one   
i think we need to get better summery of network when use API
one of function than return information of network is ENgetcount
this function only return 

```
  EN_NODECOUNT    = 0,   /**< Number of Nodes (Juntions + Tanks + Reservoirs) */
  EN_TANKCOUNT    = 1,   /**< Number of Tanks and Reservoirs */
  EN_LINKCOUNT    = 2,   /**< Number of Links (Pipes + Pumps + Valves) */
  EN_PATCOUNT     = 3,   /**< Number of Time Patterns */
  EN_CURVECOUNT   = 4,   /**< Number of Curves */
  EN_CONTROLCOUNT = 5,    /**< Number of Control Statements */
  EN_RULECOUNT	  = 6,    /**< Number of Rule-based Control Statements */
```
 if we need to get other Element Count for example pump count  dos not any thing  
i think  we must add  count for 

1. junction
2. tank
3. reservoir
4. pipe
5. cvpipe
6. pump
7. prv
8. psv
9. pbv
10. fcv
11. tcv
12. gpb
and can return valve count 
13. valve

for this porpus we need change EN_CountType  to

```
typedef enum {
  EN_NODECOUNT    = 0,   /**< Number of Nodes (Juntions + Tanks + Reservoirs) */
  EN_TANKCOUNT    = 1,   /**< Number of Tanks */
  EN_LINKCOUNT    = 2,   /**< Number of Links (Pipes + Pumps + Valves) */
  EN_PATCOUNT     = 3,   /**< Number of Time Patterns */
  EN_CURVECOUNT   = 4,   /**< Number of Curves */
  EN_CONTROLCOUNT = 5,    /**< Number of Control Statements */
  EN_RULECOUNT	  = 6,    /**< Number of Rule-based Control Statements */
  EN_JUNCTIONCOUNT=7,     /**< Number of junction */
  EN_RESERVOIRCOUNT=8,    /**< Number of reservoir  */
  EN_PIPECOUNT=9,         /**< Number of  pipe */
  EN_CVPIPECOUNT=10,      /**< Number of  cvpipe */
  EN_PUMPCOUNT=11,        /**< Number of  pump */
  EN_PRVCOUNT=12,         /**< Number of  prv */
  EN_PSVCOUNT=13,         /**< Number of  psv */
  EN_PBVCOUNT=14,         /**< Number of  pbv */
  EN_FCVCOUNT=15,         /**< Number of  fcv */
  EN_TCVCOUNT=16,         /**< Number of  tcv */
  EN_GPVCOUNT=17,         /**< Number of  gpv */
  EN_VALVECOUNT=18,       /**< Number of  valve */
} EN_CountType;  
```
and then change function EN_getcount

Note1:
although user can write owned code with use other Api function in matlab or C#  and calculate all count , for example get link count and check type of which link
Note2:
now EN_TANKCOUNT return Number of Tanks and Reservoir if accept this way we must divided it to EN_TANKCOUNT and EN_RESERVOIRCOUNT

**Comment by michaeltryby** [comment]
@milad-ghiami why do you need this level of detail? What is your use case?

**Comment by milad-ghiami** [comment]
@michaeltryby  
1.
for a big network you shod know  count of Facilities, and for a user that use API  need it to print  summery of network,
2.
API function must be comprehensive for users

**Comment by bemcdonnell** [comment]
@milad-ghiami, the node/link type data are available through the API, currently.  If you know the number of nodes, you could iterate over them and get a summary count for the various type.  I understand that this takes an extra step but a clean API should only have one place to get something, not two, in my opinion.

**Comment by milad-ghiami** [comment]
@bemcdonnell   always use of open source project , In particular when say about  engineer project , UI and UX is weak,
this oprion in   API   help to become Comprehensive

**Comment by michaeltryby** [comment]
@milad-ghiami I think one of the most important aspects of API design is "simplicity". Making an API comprehensive runs the risk of making it complicated to use. An API should be kept as simple as possible to do its job. 

If the user needs more detailed information, like @bemcdonnell has explained, they can write a custom function using the API to do so. So in a way the API is comprehensive, just not in the way you are thinking.

**Comment by milad-ghiami** [comment]
@michaeltryby    Although the leakage,quality,fire flow , PPD,...   is important , but i think write custom function for this is not good way,  Anyway, if everyone is opposed to this. We will abandon it,  :)

**Comment by milad-ghiami** [comment]
With this view, the  EN_TANKCOUNT should be deleted,
Because the genus of this variable does not interact with any other one
Of course, it's also a problem to remove it, since it may be conflict with the previous versions

**Comment by milad-ghiami** [comment]
@michaeltryby   With this view, the  EN_TANKCOUNT should be deleted,
Because the genus of this variable does not interact with any other one
Of course, it's also a problem to remove it, since it may be conflict with the previous versions

**Comment by michaeltryby** [comment]
@milad-ghiami I can tell you are eager to contribute. Our project has a large backlog of open issues. You are welcome to review the list and perhaps find one that interests you?

**Comment by milad-ghiami** [comment]
@michaeltryby 
i interested to do it , where can i found  them ?

**Comment by eladsal** [comment]
@milad-ghiami I think you are right, these counts are really needed and can be of use. I have written many programs which needed this information and  had to iterate over the node and links. Your observation about the EN_TANKCOUNT` is also correct. Why this one is there but no count for pumps or pipes? I guess this is an historic thing.

The thing is that having the count of pumps (just an example) is required but doesn't really helps you. You probably need to do something with it, right? probably go over the pumps. So here is the problem, you have no way of getting the indexes of the pumps without iterating over the links. Sad but true.

At the end of the day I would say that since the `ENgetcount` function is there, and some of the counts are already available in a variables (`Npump`) adding them to the function is easy and I see no reason not to add them. I would not go for types of valves count though.

The list of open issues is [here](https://github.com/OpenWaterAnalytics/EPANET/issues).

**Comment by milad-ghiami** [comment]
@eladsal  I think these should be add
Though I think more than that
I think we should return the pump index in an array
and The index of each element must also be returned in an array

**Comment by milad-ghiami** [comment]
what should we do?
send pull request or close issue ?

**Comment by bemcdonnell** [comment]
@milad-ghiami, as the input API gets added, there will be nothing guaranteed with respect to node / link indices.  Therefore, you should always refer back to EPANET's master list each time you need an index of something. I think that an array of object indexes will hurt more than help.  

I feel that since today you can accomplish everything you need through the existing API that you there really isn't value in adding more abstractions.  But this is meritocratic project, it's not up to me.  My experience building the SWMM API is that simple is cleaner than more complex.  to accomplish your summary in your own wrapper function, wouldn't it just be something like the following? 

```C
int count;
int error = ENgetcount(EN_NODECOUNT, &count)


int num_juncs, num_res, num_tanks;
for (i=0; i<count; i++)
{
    int nd_type;
    error = ENgetnodetype(i, &nd_type)
    if (nd_type == EN_JUNCTION ) num_juncs++;
    else if (nd_type == EN_RESERVOIR ) num_res++;
    if (nd_type == EN_TANK ) num_tanks++;
}

```

Seems like in just a few lines of code, you could accomplish this.  :-)
