### ISSUE TITLE
new function EN_setnumdemands

### ISSUE THREAD

**Issue by Mariosmsk** [OpenWaterAnalytics/EPANET#251]

**Comment by eladsal** [comment]
This is needed but we should think how to do it. By default each junction gets one demand (value 0 and no pattern). So what would the `EN_setnumdemands` function do, add multiple demands with zero flow and no pattern? What about existing demands? What if the new demands number is less than the current? to many cases...

Maybe we should consider two functions, `EN_adddemand` (which will add a new zero demand) and `EN_deletedemand` which will remove a specific demand. Any thoughts?

**Comment by Mariosmsk** [comment]
I agree with 

> add multiple demands with zero flow and no pattern

**Comment by Mariosmsk** [comment]
I agree with
> add multiple demands with zero flow and no pattern

Because you can use functions EN_setbasedemand and EN_setdemandpattern to update the new demand. Set numdemands for each node.

**Comment by eladsal** [comment]
So if the new number of demands is greater than the current you keep the existing ones and add some new ones. And when the new number is lower than the current you delete the extra demands and keep the rest. Right?

What if you want to delete just one of the demands (the second out of four)? You can set it to zero.

I still like the option of two functions.

Others?

**Comment by Mariosmsk** [comment]
#460

**Comment by michaeltryby** [comment]
Want to get this thought out and into the mix. In the list refactoring work I decided to lazy initialize the demand lists. This means that if there is no demand at the node the list remains NULL. The new generic list is a bit “heavier” than the previous implementation, lazy initialization saves memory that would otherwise get wasted. 

The Toolkit API works this way as well. When a node is added the demand list is NULL until a demand gets added. 

I have this all working on Windows. One small bug on Linux to fix and I will issue the PR.
