### ISSUE TITLE
State of the Travis CI build

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#256]
Other developers rely on EPANET building and running on Linux. Therefore we should not merge PR's that break the Linux build. Relatively easy to fix. Not that big a deal. 

Since reg tests on Travis CI have been failing for so long, people may have habituated to the failing build status. One of the reasons a benchmark hasn't been setup is I don't have easy access to a Linux box. If a developer running EPANET on Linux wanted to step forward and volunteer to maintain our Linux benchmark it would be greatly appreciated. 

I propose we stop reg testing on Travis until we can get a proper benchmark setup there. We can still build and run unit tests and get the repo into a passing state. Thoughts?

**Comment by eladsal** [comment]
This is exactly what happened. Since travis fails for a long time I ignored it completely. If we know the build should be fine and only tests are failing we should stop the tests until it is fixed.

I'm looking at the log but can't find the line it says the build fail. @michaeltryby can you link to the line please?

**Comment by michaeltryby** [comment]
So build and unit testing are live on Travis and in a passing status. We need an EPANET Linux build maintainer to keep the benchmark up to date there.
