### ISSUE TITLE
new API function to insert additional hydraulic step

### ISSUE THREAD

**Issue by attilabibok** [OpenWaterAnalytics/EPANET#295]
Hi!

I'm new to the community and started working on the function mentioned above. It could be useful while handling large-scale models including various data sources with the toolkit. Similar to EN_nextH(), but with an additional input variable for the desired hydraulic step.

It is just an extra condition in the timestep() function like:
`/* Revise time based on user provided input */`
`t = TimeWhenIWantTheExtraStep - time->HTime;`
`if (t>0 && t < tstep) {`
`    tstep = t;`
`}`

"Overloading" the ENnextH() and passing TimeWhenIWantTheExtraStep doesn't seem elegant though...
Adding another field to  time_options_t struct seems better, which can be modified by EN_settimeparam() and another value for EN_TimeProperty. However, it feels a bit weird for me because it is not a constant property...

I've created a branch 'dev-insert' for this "issue".

**Comment by michaeltryby** [comment]
@attilabibok Interesting idea. Could you explain your use case in greater detail? Do you want to insert a time-step so you can have your modeled data match the sampling frequency coming from a data source?

**Comment by LRossman** [comment]
Why can't one just use the `EN_settimeparam` function to set a new value for `EN_HYDSTEP` at the point in time where the extra step is desired, and then set it back again?

**Comment by michaeltryby** [comment]
@attilabibok I believe the RTX libraries already provide functionality for meshing data frequencies and modeling time steps as you are describing.

**Comment by samhatchett** [comment]
Thanks for the ideas, @attilabibok ! 

EPANET-RTX does do some data frequency meshing, but it does so using the convention proposed by @LRossman - by setting the timestep duration every timestep:
https://github.com/OpenWaterAnalytics/epanet-rtx/blob/c5645e3d49b8e96296da45932351c3711326b7a7/src/EpanetModel.cpp#L889

However, I think that the very fine-grained control of time stepping RTX does via the epanet API required some changes within epanet (we had to be able to re-set the overall duration and current time to zero at every step in order to make things work right). This all presupposes that we are ignoring patterns and time-based controls, which RTX does.

So I suppose at the end of the day, the proposal at the top of this issue is not fully supported by the EPANET API yet, depending on what the requirements are.

**Comment by attilabibok** [comment]
Thank you all for your feedback!

My initial idea was to give flexibility to the user altering (or inserting extra) timesteps without the effort of calculating the necessary time-step length in the user's implementation, but simply giving the absolute simulation time in seconds where the step is needed. Though, I think RTX has a more robust solution for this "issue".

**Comment by samhatchett** [comment]
sounds like this is a "fringe" use case and there's a workaround.
