### ISSUE TITLE
Can we replace the error manager with something simpler

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#304]
An error manager (`errormanager.c`) was added into the code some weeks ago. I have some issues with it:

1. I cannot get the `EN_checkError` function, which uses the manager's `check_error` function, to return a valid string holding the error message.
2. The manager allocates memory for its error message string in its `check_error` function and expects the API user to free it in their calling code -- this seems like an invitation for memory leaks.

It seems like a simpler approach is to:

1. Define a new `ErrorStatus` variable in the `EN_Project` struct that holds the latest error/warning code found.
2. Replace all of the` set_error` function calls in `epanet.c` with simple assignments to `ErrorStatus`.
3. Add the six warning messages (codes 1 - 6) to `errors.dat`.
4. Remove the `errorLookup` function in `epanet.c` as well as the error manager files.
5. Redefine `EN_checkError` to simply return the value of `ErrorStatus`.
6. The existing `EN_geterror` function can be used to obtain the text of the error message associated with the code returned by `EN_checkError`.

I'm ready to implement this if it sounds like an improvement.

**Comment by michaeltryby** [comment]
@LRossman have you fetched and pulled lately. This bug was fixed in PR #285. 

As you know the UI's are being migrated to Python, making integration of our dlls with Python pretty important. `errormanager.c` is used across all of the EPANET and SWMM Output and Toolkit libraries to provide a consistent interface for automatic exception generation in the Python wrappers. So when an error occurs a Python Exception with the error number and message string automatically gets thrown. It's may seem a little complicated because I am reusing the code across 3 of the 4 libraries I am wrapping.  

The changes you are proposing would break the python wrappers I have been developing. The memory being allocated gets automatically released in the Python wrapper calls right after it gets passed from C to Python. It has been tested and there are no memory leaks. I will double check to make sure the memory is being freed properly. 

I would prefer that you do **not** go forward with the changes you are proposing. Thanks!

**Comment by LRossman** [comment]
Ok @michaeltryby, I will not go forward on this.
