### ISSUE TITLE
Bug in function ENdeletelink

### ISSUE THREAD

**Issue by Mariosmsk** [OpenWaterAnalytics/EPANET#312]

**Comment by Mariosmsk** [comment]
for test:
ENopen
ENgetcoord
ENdeletelink
ENgetcoord <-- return zero

**Comment by LRossman** [comment]
@Mariosmsk could you please elaborate a little more on what the bug is. In the test code segment you provided I'm not sure what `%all` means. If in fact you were trying to retrieve coordinates for link 9 after it was deleted, the `ENgetcoord `function only applies to nodes, so you were actually retrieving the coordinates of Node 9 successfully. If this interpretation is correct then there is no bug. But maybe I'm missing something.

**Comment by Mariosmsk** [comment]
@LRossman, when I want to delete a pipe (e.g. link index = 9) then the function deleted the pump (with index 13) and make duplicate pipe ID with the link who deleted.
Also, by this test:
```
ENopen("Net1.inp")
ENsaveinpfile(test1.inp');
ENdeletelink(7);
ENsaveinpfile(test1.inp');
```
result:
![bug](https://user-images.githubusercontent.com/2945956/47373035-ae08a800-d6f3-11e8-8a04-8ff4106b2e21.png)
