### ISSUE TITLE
Eliminating the need to use WITH_GENX and epanet2_export.h in client code

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#376]
I found a way to modify the cmake scripts and the EPANET2 header files so that client C/C++ apps can use `epanet2.dll` without having to define `WITH_GENX` or include `epanet2_export.h` in their builds. (Note: this does not apply to VB/VBA/Delphi apps which still need a version of the DLL built with a `def ` file.) The required changes are:
1. Remove all lines that contain `WITH_GENX` in all of the cmake scripts and in the pre-processor statements in `epanet2.h` and `epanet2_2.h`.
2. Re-write the pre-processer statements that define `DLLEXPORT` in `epanet2.h` and `epanet2_2.h` as follows:
```
#ifndef DLLEXPORT
  #ifdef WINDOWS
    #ifdef epanet2_EXPORTS
      #define DLLEXPORT __declspec(dllexport) __stdcall
    #else
      #define DLLEXPORT __declspec(dllimport) __stdcall
    #endif
  #elif defined(CYGWIN)
    #define DLLEXPORT __stdcall
  #else
    #define DLLEXPORT
  #endif
#endif
```
This works because the Visual Studio compiler automatically adds `/D epanet2_EXPORTS` to its command line.

After making these changes I rebuilt the project using cmake with Visual Studio 2017 and the resulting command line executable `runepanet.exe` worked as before. I then locally rebuilt one of the test projects (`netbuildertest2.cpp`) without using `WITH_GENX` or `epanet2_export.h`. The resulting executable ran successfully. Finally, I did a test commit and PR of these changes to the `dev` branch and it passed the CI tests.

Does anyone have an objection to merging these changes into `dev`?

**Comment by LRossman** [comment]
There is also supposed to be a `cmake` target property, _WINDOWS_EXPORT_ALL_SYMBOLS_, that eliminates the need to add `__declspec` directives to exported functions as it will create a `def` file for the target and link against it [(see this link)](https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/). If I understand this correctly, it means that `cmake` can be used to build a DLL that can be used with VB/VBA/Delphi. However when I modified the API header files to define `DLLEXPORT` as simply `__stdcall` and added the following line to `CMakeLists.txt`:
```
set_target_properties(epanet2 PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS TRUE)
```
after the `add_library` line, all I got were a bunch of cryptic error messages when I ran `msbuild`. Maybe someone can research this further since it would be great if `cmake` could create a DLL that can be used by all types of toolkit clients.

**Comment by LRossman** [comment]
Since I can't get cmake's _WINDOWS_EXPORT_ALL_SYMBOLS_ to work, it is possible to create a DLL with cmake that works with VB/VBA/Delphi by modifying the following line of `CMakeLists.txt`:
```
add_library(epanet2 SHARED ${EPANET_LIB_ALL} ${PROJECT_SOURCE_DIR}/include/epanet2.def)
```
where `epanet2.def` is the `def` file created by @eladsal that has been copied into the project's `include` folder. (Note: right now this file only contains declarations for the legacy API).

I've tested the DLL that cmake produces with this change on both the existing EPANET 2.00.12 UI, a small Excel/VBA example, and one of the project's C++ test examples - all worked just fine. This change avoids the need to make a separate build using the script in the `win_build` folder to support 32-bit apps built with VB/VBA/Delphi.

**Comment by michaeltryby** [comment]
@LRossman As far as I know I'm the only client using `WITH_GENX` since I'm the one that set it up for the Python wrapper build. After many objections from the community `WITH_GENX` was made opt-in meaning clients aren't required to use it. Since that is the case, why does it need to be eliminated? 

I'm happy with my build setup on the Python side of things and since it has no impact on other clients I don't see any advantage to modifying it as you describe.

**Comment by LRossman** [comment]
@michaeltryby a couple of things:
- C/C++ clients do need to use WITH_GENX and epanet2_export.h when building their apps, otherwise DLLEXPORT doesn't get defined as __declspec(dllimport) and the link step will fail - I know because I've tried it.
- Can you try my modified header, which defines DLLEXPORT as  __declspec(dllimport) without using WITH_GENX, in your Python wrapper and see if it works?
- If you still need to work with WITH_GENX and the accompaning epanet2_export.h, I can change my proposed pre-processor declarations for the toolkit headers to be:
```
#ifdef WITH_GENX
   #include "epanet2_export.h"
#else

  // --- define WINDOWS
  #undef WINDOWS
  #ifdef _WIN32
    #define WINDOWS
  #endif
  #ifdef __WIN32__
    #define WINDOWS
  #endif

  // --- define DLLEXPORT
  #ifndef DLLEXPORT
    #ifdef WINDOWS
      #ifdef epanet2_EXPORTS
        #define DLLEXPORT __declspec(dllexport) __stdcall
      #else
        #define DLLEXPORT __declspec(dllimport) __stdcall
      #endif
    #elif defined(CYGWIN)
      #define DLLEXPORT __stdcall
    #else
      #define DLLEXPORT
    #endif
  #endif
  
#endif  
``` 
so that WITH_GENX is there if you need it and if you don't then C/C++ client apps will still be able to link with the toolkit by just using epanet2.lib like they always did back in the v.2.00.12 days.

**Comment by michaeltryby** [comment]
@LRossman so let me get this straight. The issue as you see it, is that the current cmake generated `epanet.dll` can't be linked against like back in 2008? Honestly, I don't share that concern. 

Devlopers building clients not wishing to use `epanet2_export.h` are welcome to use the win_build script also being supported by the project.

**Comment by LRossman** [comment]
Yes, @michaeltryby, that is basically the issue. Right now we are putting more obstacles in the way of toolkit users, who are not likely to be professional programmers, by asking them to have to mess with WITH_GENX and epanet2_export.h or have them re-compile the toolkit, or we distribute different versions of the DLL produced from different builds using the same compiler -- that's crazy. All of this just to support your Python wrapper? I'm offering a simpler way. Why are you so opposed to it?

**Comment by michaeltryby** [comment]
@LRossman My understanding is that way back in the day linking with EPANET required a `.def` file. All this controversy about the `epanet2_export.h` file strikes me as a red herring. Depending on how you look at it things, an argument can also be made that `epanet.def` is superfluous.  

The real issue is that VB requires linking with a `.def` file but building the Python wrappers requires linking with a `.lib` file. Therefore, we somehow need to support both linking approaches. 

The former is supported using the win_build script while the later is supported using our cmake configuration. It's not ideal, but the project's needs with respect to VB and Python are both currently supported.

**Comment by michaeltryby** [comment]
@LRossman Toolkit users who aren't professional programmers will be using Matlab, R, and Python.

**Comment by LRossman** [comment]
@michaeltryby you didn't read my comment thread carefully enough. My new CMakeLists script includes a def file while the modified toolkit header files properly defines DLLEXPORT when used as an C/C++ import library. So both birds are taken care of with one stone. I've tested this by using the DLL so produced in both VBA, Delphi, and C++.

**Comment by michaeltryby** [comment]
@LRossman well test it for Python and if it works than I guess you solved it!

**Comment by LRossman** [comment]
I tested the DLL built with my new CMakeLists script & toolkit headers on an old Excel/VBA app I had and it ran fine, so I assume it would do so with VB 6. @eladsal could probably test it on a VB.net project if he has one, or I could try myself at some point. I used the same DLL to replace the old 2.00.12 DLL with the current EPANET Delphi UI and again it worked just fine. Please note that the def file used to build the DLL only includes the legacy toolkt functions, so it won't work if a VB/VBA/Delphi app tries to use one of the new thread-safe functions (we can always add those to the def file at some point).

Regarding a C/C++ app, one only has to include a toolkit header file and link with epanet2.lib. I tested the same DLL as used above on the test_net_builder_2 project, which is written in C++ and uses the thread-safe functions, and again everything worked ok. There was no need to define WITH_GENX or make epanet2_export.h available.

I appreciate your willingness to test the new CMakeLists and toolkit headers on your Python wrapper. Please let me know if there's any way I can help, perhaps by tweaking these files in case there are issues.

**Comment by michaeltryby** [comment]
VB6 was discontinued by Microsoft 10 years ago. So that begs the question, how long is it necessary for us to support it?

**Comment by eladsal** [comment]
VB6 is like VBA.

**Comment by michaeltryby** [comment]
@LRossman You seem to be misunderstanding me so I will try to be more clear. I am completely satisfied with the current cmake build configuration. I don't share your concern that defining `WITH_GENX` and including `epanet2_export.h` is an issue. I can't speak for @eladsal and @Mariosmsk but my understanding is that they prefer using their `win_build` script. Therefore, it is my belief that the status quo is satisfying everyone's needs. Please feel free to chime in if this is not the case. 

We have already established that Delphi can be supported using the  `epanet2.dll` built with the current cmake configuration by changing the calling convention in the Delphi code. Seeing as how Microsoft discontinued VB/VBA 10 years ago supporting it is not a concern of mine; but I don't have a problem with @eladsal efforts to maintain support for it since it's important him. It would be neighborly if the same courtesy were extended to me with respect to the Python wrapper build.  

It is regrettable that you prepared your PR prior to understanding different developer's preferences with respect to the build.

**Comment by michaeltryby** [comment]
@eladsal Thanks for the feedback! While I was on furlough I discovered [Microsoft Build Tools](https://blogs.msdn.microsoft.com/vcblog/2017/11/02/visual-studio-build-tools-now-include-the-vs2017-and-vs2015-msvc-toolsets/). Have you heard of it? 

The compiler is no longer installed with the Windows SDK. MS Build Tool is the current preferred way to install it without having full blown Visual Studio on your computer. Therefore, a one-click build would have two dependencies (cmake and MS Build Tool) as long as unit tests were not being built. Is that acceptable to you?  

I honestly don't understand peoples aversion to the `epanet2_exports.h` file. If it were checked in, it would be no different than `epanet2_enum.h` and no one has a problem with that. If we adopted the export header, we could completely eliminate the pre-processor boiler plate required to define `DLLEXPORT` and let the build system deal with it. If it would make people feel better we can add it to the include folder.   

Using MS `lib` tool `.def` and `.lib` files are completely interchangeable. It is my understanding that one can be generated from the other and vice-versa. I prefer the `.lib` file format since it is compiler generated we no longer need to manually update the `.def` file. 

Therefore, the only difference between the cmake and the win_build setups is the calling convention being used. I think VB/VBA requires `stdcall`. This can be satisfied using the `/Gz` switch on the Visual C compiler. 

Thoughts?

**Comment by LRossman** [comment]
@michaeltryby PR's can always be cancelled before merging, so no harm no foul. As far as I can tell, it's only you and I who disagree on the build system. My new build system is clearly superior to the current one, being able to produce a single DLL that works with multiple languages without resorting to extra symbols and header files that a client must use. Please try my new build system with your Python wrapper and let's work together to improve things.

**Comment by michaeltryby** [comment]
Question for the VBA guys, how do you call a 64-bit dll from VBA? The references I'm looking at say `__stdcall` is accepted and ignored when compiling 64 bit.

**Comment by LRossman** [comment]
I see that the `dev` branch was updated to now include the Python wrapper functions as part of the toolkit DLL. My modified cmake build system, which no longer requires `WITH_GENX/epanet2_export.h`, has been updated (and simplified) accordingly. Once again, the single DLL it produces works with VB/VBA, Delphi, and C/C++. For those who want to test it, here are the changes required:

- Copy `epanet2.dev` from the `win_build/winSDK` folder to the `include `folder.

- In the main `CMakeLists.txt` file, replace the `add_library` line with:
```
if(NOT WIN32)
    add_library(epanet2 SHARED ${EPANET_LIB_ALL})
else(NOT WIN32)
    add_library(epanet2 SHARED ${EPANET_LIB_ALL} ${PROJECT_SOURCE_DIR}/include/epanet2.def)
endif(NOT WIN32)
```

- In the same file delete all lines following `# create export lib so we can link against dll using Visual Studio`.

- In `\run\CMakeLists.txt` delete` add_definitions(-DWITH_GENX)`.

In both `epanet2.h` and `epanet2_2.h` replace all lines between `#define EPANET2_2_H` and `#include "epanet2_enums.h"` with:
```
#ifndef DLLEXPORT
  #ifdef _WIN32
    #ifdef epanet2_EXPORTS
      #define DLLEXPORT __declspec(dllexport) __stdcall
    #else
      #define DLLEXPORT __declspec(dllimport) __stdcall
    #endif
  #elif defined(CYGWIN)
    #define DLLEXPORT __stdcall
  #else
    #define DLLEXPORT
  #endif
#endif   
```

- In `epanet_py.h` delete` #include "epanet2_enums.h"` and` #include "epanet2_export.h"`.

- Use the following `#includes` in `epanet_py.c` in the order listed:
```
#include "epanet2_2.h"
#include "epanet_py.h"
#include "util/errormanager.h"
#include "text.h"
#include "types.h"
```
Note that the Python wrapper functions are exported using the `stdcall` convention. If this is a problem it's simple enough to replace their `DLLEXPORT` symbol with another one (like `EPANET_PY_API`) and repeat the `DLLEXPORT` declarations but have them refer to the new symbol (e.g. `EPANET_PY_API` instead of `DLLEXPORT`) and drop the `__stdcall`  from them.

**Comment by michaeltryby** [comment]
Thank you for your efforts, however, like I've said before I'm not interested in eliminating `WITH_GENX` and `epanet2_export.h`. I believe essentially the same thing can be accomplished by replacing your DLLEXPORT definition with `epanet2_export.h`, and specifying the /Gz switch in the build and I prefer that solution over yours.

**Comment by LRossman** [comment]
@michaeltryby can you please provide a logical argument why your approach is better than mine. While they both accomplish the same thing (maybe), mine does so in a simpler, more direct and compact manner (less switches and include files) while imposing less of a burden on toolkit client developers. I thought this was supposed to be a collaborative project, so why do you get final say over its design?

**Comment by michaeltryby** [comment]
@LRossman you are making such a big deal out of nothing. This is a non-issue as far as I'm concerned.  

1) `epanet2_export.h` - If adopted it we can eliminate the custom `DLLEXPORT` definition which is just a bunch of preprocessor boiler plate. 

2) Calling convention - It does not hurt anything to use the /Gz compiler switch. Using this approach we can make the desired calling convention a build option. (FYI: `__stdcall` goes away in 64-bit).

3) Linking - as far as the linker goes a `.def` and a `.lib` are six and one half dozen of the other. By adopting the `.lib` for linking we can phase out the `.def` file and eliminate maintenance of it. Perhaps we we can generate the `.def` file on the fly instead. 

4) Python - your solution ignores the requirements of the Python wrapper build. I need the `.lib` file to link and the cmake generate exports command is how it gets created.

**Comment by LRossman** [comment]
@michaeltryby regarding your points:

1. Look at the contents of `epanet2_export.h`. The relevant part of it contains the same "boilerplate" as my new declarations in the toolkit header files (minus the` __stdcall` declaration).
2. Using `/Gz` is overkill.
3. C/C++ needs to link against a` .lib `file (even if the library was built with a `.def` file). VB/Delphi can't/doesn't use a` .lib` file -- they need a DLL built with a` .def` file (and the stdcall convention).
4. My new build system still generates a `.lib` file (in the `\build\lib` folder). That's what I used when I built my test C++ app using the DLL from the new system.

Finally, if this is such a non-issue to you then why are you objecting to my approach?

**Comment by michaeltryby** [comment]
@LRossman 

1) Exactly why are you copying and checking in something that gets generated. 
2) I disagree. 
3)  `.lib` and `.def` files the dll's are the same in either case the only difference is the calling convention
4) Test it and see if it works. 

I keep having to talk about it because you won't give it a rest.

**Comment by michaeltryby** [comment]
Also, unless you are using the cmake generate exports command the `.lib` file produced doesn't contain all the necessary information.

**Comment by michaeltryby** [comment]
@LRossman This is a collaborative project. Sometimes people disagree. You have merged 9 PRs in the last 2 months. 9 - 1 is a good record.

**Comment by eladsal** [comment]
True, but closing a PR or an issue like you have done isn't "collaboration". Good night.

**Comment by michaeltryby** [comment]
@eladsal It can be reopened with a mouse click at any time.

**Comment by michaeltryby** [comment]
You are right.

**Comment by LRossman** [comment]
Although I think I've clearly demonstrated that my modified cmake build system is better than what is used now, and my tests of the DLL it produces have been successful on VB, Delphi, and C/C++ apps (a Python test is beyond my means), there appears to be a lack of consensus from the team to adopt it. Therefore I will lay it to rest (for now) and close this issue.

**Comment by michaeltryby** [comment]
@LRossman Unless I’m mistaken, I think you will find that the import library generated using your setup and the one generated using the generate exports command are not equivalent and interchangeable as you claim.

**Comment by LRossman** [comment]
Yes, the two .lib files aren't the same (size produced by current build system is 65 K, while its 90 K with the new one). I attribute this to the inclusion of the __stdcall directive and the .def file in the new system. I've attached a zip file containing the C++ example that I successfully built in VS 2017 using the results of the new build system. This is a version of test_net_builder_2 that doesn't rely on the Boost library. It creates a network model through function calls, solves it, writes it to file, reads it back from file, solves it again, and compares the two solutions. I suggest you take a look.
[NetBuilderTest2.zip](https://github.com/OpenWaterAnalytics/EPANET/files/2824833/NetBuilderTest2.zip)

**Comment by LRossman** [comment]
To expand on the .lib file issue, if I remove the `__stdcall `declaration from my modified toolkit headers (`epanet2.h` and `epanet2_2.h` -- see the code listing several comments above) and I remove the reference to `epanet2.def` in the `add_library` command of the CMakeLists file, then my modified build system is exactly the same as the current one that uses the` GenerateExportHeader` command. The .lib files  produced by the two systems are the same size (they are not byte identical though, since every time the .lib file gets generated it contains a new 10-digit "magic number" in it, even when using the same build system).  Both .lib files will successfully link with C/C++ apps that use the toolkit DLL (as tested on the net_builder_2 test example I provided above). What this shows is that if we simply substitute the relevant portion of the` epanet2_export.h` declarations directly into the toolkit headers (we're talking only 5 lines here) we avoid the need to use `WITH_GENX` and an additional header file.

So what does including `__stdcall` and `epanet2.def` in the new cmake build system buy us? In the latter case it allows the toolkit DLL to be used with non-C/C++ languages that don't use `__declspec(dllexport)` or a .lib file to identify the names of the importable functions in the DLL. As for `__stdcall`, I believe it's only needed for VB6/VBA apps (Delphi doesn't need it and I think neither does VB.net or C#). But since we're committed to backwards compatibility, we need to include it (or else distribute two versions of the toolkit).

So I still stand by my contention that my new cmake build system is better than the one we use now since it produces a single DLL that can be used with multiple languages (under Windows) without requiring that clients use special pre-processor directives or additional header files when building their apps.

**Comment by michaeltryby** [comment]
Historically, the OWA fork has placed a greater emphasis on experimentation and less on backwards compatibility. It’s fair to say that you are more committed to it than I am. 

I don’t have a problem with things not being exactly how they were 10 years ago. The project needs to evolve.

**Comment by michaeltryby** [comment]
@LRossman what I realized over the weekend is that there is enough flexibility here that everyone can get what they want/need. I also realized that since we have three different APIs (EN, EN_, and py) it doesn't make sense to have one dll with over 300 entry points. 

So what I have done is incorporate your ideas on support for library creation with the `.def` file into a default `epanet2` library target that includes the 2.0 and 2.2 APIs. And created a custom `epanet_py` library target that is setup to my requirements. 

Problem solved! :smile:  

I will wrap up testing and then create a PR for you all to look over.

**Comment by LRossman** [comment]
@michaeltryby **Excellent!** When I saw that you added the Python/SWIG API into the main EPANET library I had a similar thought -- wouldn't it be better to place the Python stuff in a separate library given its special purpose nature. I look forward to reviewing your PR.
