### ISSUE TITLE
support for ISO-8601 time format

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#4]
support for date/time would allow multi-day simulations with time-based controls that do not require you to use decimal hours. this should apply to any rule or setting that understands CLOCKTIME:
- controls
- rules
- times (start clocktime)

**Comment by michaeltryby** [comment]
This is a good idea. Having to mess around with decimal hours is a nuisance. My only concern is that ISO-8601 carries with it features that aren't really useful for most use cases. For example, do we really need support for time-zones and UTC? This represents unnecessary complexity.

How do you propose implementing this?  Boost?

**Comment by samhatchett** [comment]
I suggest looking at timezone support because distribution systems exist geographically within these timezones. This is all related to moving toward the ability to export a real-time operational model that correctly mimics behavior during a particular time frame from the historical record. I think it makes sense to fully capture the date and time of particular control actions because they really happened at that date/time. 

Also, I might be running a simulation for Phoenix while sitting in Shanghai -- so the report generation shouldn't assume local time, but should reflect Phoenix time. Or maybe I'm analyzing the effects of an earthquake or flood on a distribution system - I would want to know precisely when things happen and be able to coordinate among different records without having to do time-math in my head.

BOOST has some pretty good time and calendar features - it's always a pain to support, but it's the sort of thing that degrades gracefully if you don't want to use ISO format.

**Comment by jamesuber** [comment]
Yeah I think these are good arguments. Data-model integration is forward thinking and important (at least to us) and every piece of data in a database was an actual point in time and deciphering that inevitably requires TZ. Since you didn’t mention it, I’ll add that sam found some nice tz support in python via arrow, for future python tools. 
 <http://www.citilogics.com/> JIM UBER <mailto:jim@citilogics.com> • 513.368.6303 <tel:513-368-6303> • CITILOGICS.COM <http://www.citilogics.com/>

**Comment by michaeltryby** [comment]
I like the idea of keeping the **simulation engine** as simple and dependency free as possible. I think it should be one of our most important design objectives. Why? Because it's already really complicated. We need to actively manage its complexity. What you choose to do in your application that use it is another matter entirely. So you really need to wear two hats. 

To me, introducing a dependency like BOOST to add full ISO-8601 support for controls seems like a lot of unnecessary complexity at the engine level. The engine currently operates on relative time, hence controls are written in relative time. Simple. 

I agree with you. Time deltas and decimal hours aren't user friendly. They make the controls interface difficult and finicky to use. People don't think in decimal time and time deltas become difficult to use when the simulation period gets longer than a few days. 

What is the simplest and most straightforward way to fix this problem without introducing unnecessary complexity/dependencies in the simulation engine?

**Comment by samhatchett** [comment]
great points @michaeltryby - i completely agree. i feel that the hydraulic engine should be a standalone library. super fast, super efficient. on top of that, we need the ability to parse INP files, create networks, and run simulations using the toolkit. these should really be separate projects.

in creating this enhancement issue, i'm not at all suggesting that somebody write code - just mean it to be a placeholder for the admittedly GREAT idea of supporting "real" time concepts - for when these different streams of thought get a little more firm.

**Comment by dweintrob** [comment]
Although there are work arounds, it would be helpful if there would be support for the Day-Of-Week since many operating rules depend on the day of week.
i.e. The Starting day could be set and computed during the simulation and also could be used by the rules.

**Comment by samhatchett** [comment]
closing due to staleness. also 8601 should be a higher-level feature
