### ISSUE TITLE
Small issues that don't cause problems but should be cleaned up (IMHO)

### ISSUE THREAD

**Issue by accumodel** [OpenWaterAnalytics/EPANET#40]
See if you agree with the following:
1.  Issue in adjustdata() function (input1.c) line 305

304  /\* Use default pattern if none assigned to a demand */
305     for (i=1; i<=Nnodes; i++)

Since you cannot place a demand on a tank/reservoir, there is no need to loop clear through all of the nodes.  Just go through to Njuncs.
1.  Issue in valvecheck() function (input3.c) line 1782

1781  /\* Examine each existing valve */
1782     for (k=1; k<=Nvalves; k++)

Should read "for (k=1; k<Nvalves; k++)"   so the function does not compare the current valve to itself.  Probably does not ever cause an issue, but it would be good to clean it up

**Comment by eladsal** [comment]
"need for speed"

@accumodel I think you are right in both cases. The first will save going over the list of tanks one time and the second will save running over the valves for one time. Have you made some tests with the changed code?

BTW, which branch are you referring to with these line numbers? it is better to look at `dev-2.1`.

**Comment by accumodel** [comment]
Sorry for the confusing line numbers.  This is the first time I am getting involved in an open source project.  I am just learning git now as well.  

The line numbers in my comments refer to the original EPANET source code from 2008 available on the EPA website.  I will make reference in the future to the current open source version hosted here on github.  I have ported EPANET over to Python to play around with new features since that is my strongest language.  I just noticed these items while I was translating the code and due to the way I have implemented demand information in Python, it was giving me an error.  Leaving the code as-is does not cause any issues in the C version, it just seems unnecessary to do any more looping than necessary.  I am wondering if it was allowed at some point to assign demands to Tanks.  I have only been in the EPANET world since 2005 so I don't know the complete history.

**Comment by mauriziocingi** [comment]
@accumodel if you play with epanet/Python you can try Python wrapper for Epanet library in https://github.com/OpenWaterAnalytics/epanet-python

Instead of rewrite all code you can call epanet toolkit functions (in dll or shared object) from pure python programs. No need to translate....

**Comment by accumodel** [comment]
@mauriziocingi I have previously tried the wrapper but you are limited to the toolkit functions.  It has been a good exercise to port EPANET to Python.  I understand EPANET a lot better now.  I am also getting closer to C speed by implementing Cython in parts of the Python code.

The Python port also allows me to quickly test new functionality.  I can share with the community when I am finished with it if anyone is interested.

**Comment by mauriziocingi** [comment]
Ok, it depends on what you mean with "limited toolkit functions". It is limited to exported functions (and that is the way libraries are built) with Windows, unlimited access with gcc/Linux. You simply have to add few lines of ctypes declaration in module and new functionality are immediately accessible.

For sure I'm interested at your work.....

**Comment by eladsal** [comment]
I think the first point in the original comment is still valid in `input1.c` line [334](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/src/input1.c#L334). Is there a need to go over all nodes or just the junctions?

**Comment by eladsal** [comment]
Any thoughts about this open issue?

**Comment by samhatchett** [comment]
I would defer to @LRossman to say more definitively whether the proposed change would have any adverse effect. Demands are still relevant for Tank nodes, just not sure exactly what the tanks are going to depend on.

**Comment by LRossman** [comment]
The first proposed change, to not loop through Tanks/Reservoirs when assigning the default demand pattern to nodal demands, makes logical sense but it's not worth changing the code at this point. Tanks/Reservoirs have a `NULL `Demand property and the code already checks for this before trying to assign the default pattern. The speed up in execution by making the change would be imperceptible.

The second proposed change, to ignore the last added valve when checking the validity of its connections in the `valvecheck()` function, will cause problems when the latter is called by `EN_setlinktype()` or `EN_setlinknodes()` since the valve being checked may no longer be the last one added. However, there is a small problem when `EN_setlinknodes()` is called for a PRV or PSV with the new set of nodes the same as the existing set. In that case `valvecheck()` will return with an error condition. The simple fix is to add a check to `EN_setlinknodes()` that sees if a link's set of nodes actually changes and exit the routine if there is no change. A PR will be forthcoming.

**Comment by samhatchett** [comment]
So it sounds like, in the end, the proposals in this issue are either problematic or of negligible impact. Vote to close?

**Comment by eladsal** [comment]
+1

**Comment by LRossman** [comment]
Yes I vote to close. (The `valvecheck() `issue was fixed in PR #561.)
