### ISSUE TITLE
Allow access to binary output results while keeping project open

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#407]
LRossman states in Issue #405, “I believe it's really important that client apps have direct access to the output results file without having to close down the entire project. In lieu of this we could add two new functions, EN_getnoderesult and EN_getlinkresult, that return a computed result for a given variable at a given time period. However this option probably wouldn't be as efficient as having direct access to the file.

If a client app can't get access to all of the results of a run (while the project is kept open) it would have to capture results at each reporting time period (using the existing EN_getnodevalue and EN_getlinkvalue) as the simulation unfolds and save them somewhere so that interactive display of the results (in graphs and tables) could be done efficiently.”

**Comment by LRossman** [comment]
My attempts to implement this feature (by strategically closing and re-opening the output file in several toolkit functions) is failing the Travis CI check on Linux (while passing the Windows check). As I don't have access to a Linux machine at this time, trying to fix the issue could be problematic. What would be a reasonable amount of time to spend on getting this feature to work so as not to significantly delay the release of v.2.2?

**Comment by michaeltryby** [comment]
Is there someone listening who builds/runs EPANET on Linux that can assist us in trouble shooting this bug?

**Comment by gonccalo** [comment]
I think I got it.
 In `EN_closeQ` you close `p->outfile.OutFile` and put the pointer to `NULL` without checking if it is the same as `p->outfile.TmpOutFile`. So in `EN_close` when you check `if (out->TmpOutFile != out->OutFile)` it will be true because `out->OutFile` is `NULL` when in fact it was pointing to the same file and it is already closed. In my machine fixing this makes the test_reent.cpp pass

**Comment by LRossman** [comment]
@gonccalo your fix works! I refactored closing the output file into its own function `closeoutfile` in project .c since the same code is used both in `EN_closeQ` and in `openoutfile`. The code now passes both CI checks. I also tested the re-built DLL with a client app that accesses the output file while the project is still open and that seemed to work OK too. Thank you @gonccalo !

**Comment by gonccalo** [comment]
Glad to help!

**Comment by LRossman** [comment]
This issue has been successfully resolved by PR #408.
