### ISSUE TITLE
Toolkit evaluates RULES differently

### ISSUE THREAD

**Issue by sm-rana** [OpenWaterAnalytics/EPANET#409]
The RULES are evaluated differently than the Epanet 2.1. Consider the following Rule:

; WSR FILLING
RULE WSR_FILL
IF LINK WSR_FILL STATUS IS OPEN
AND LINK WSR_HOLD STATUS IS CLOSED
AND SYSTEM CLOCKTIME >= 10:00 PM    ; ###WSR FILL START###
OR SYSTEM CLOCKTIME <= 7:00 AM      ; ###WSR FILL END###
THEN LINK V102 STATUS IS OPEN
AND LINK V102 SETTING IS 160.0      ; ###WSR FILL LOSS COEFFICIENT### (22.5% open)
ELSE LINK V102 STATUS IS CLOSED
PRIORITY 1

At time 0, the IF clause should be true and the valve V102 should be set to 160, which the Epanet 2.1 GUI does, but the Epanet 2.2 toolkit (utilized via epanet-python) does not. 

I realize this is a dev branch, so if behavior has changed on purpose I would appreciate knowing. Otherwise perhaps its a bug introduced in the changes for 2.2

**Comment by michaeltryby** [comment]
@sm-rana Our unit tests and reg tests don't cover controls very well. It's possible that this is a bug.

**Comment by sm-rana** [comment]
@michaeltryby After going through the source code and comparing the behavior of the dev branch with epanet 2.0012,  I think I have figured out (with help from @jamesuber ) the cause of the difference in behavior. The rules from the inp file are stored in the "Struct Srules" and "Struct Rules" in reverse order than in the Epanet 2.0012. The the order in which an action is taken on a link matters very much. For example in the THEN section of the rule example I posted above, "Link V102" should first be turned "ON" and then set to "160". Currently due to reversal in the storing order of actions, the Link V102 is first set to 160 and then turned ON, and therefore the link is never set to 160.

A simple test proved this hypothesis. I simply flipped the two lines in the INP file and then it worked as it was supposed to! I also have a fix for the source code, so @michaeltryby I can share that with you, if you are interested.

**Comment by LRossman** [comment]
@sm-rana I believe the issue only occurs when the same link has two or more actions assigned to it in either the `THEN` or `ELSE` section of a rule. Normally there would be no reason to do that. Using your example, you really only have to use the `LINK V102 SETTING IS 160.0` as this will automatically cause the valve to no longer be closed. This modified rule will give the same result in both 2.00.12 and 2.2.

In 2.00.12 the action clauses are stored in the reverse order from how they appear in the rule while in 2.2 they are in the same order as in the rule statement. So in 2.00.12 the `LINK V102 SETTING IS 160.0` is added to the action list first. Then the `LINK V102 STATUS IS OPEN` tries to be added, but because Link V102 already has an action on the list with the same rule priority this action doesn't get added to the list. When the actions on the list are taken, V102 has its setting changed to 160 which automatically causes it to no longer be closed.

In 2.2 the first action added to the list is `LINK V102 STATUS IS OPEN`. This prevents `LINK V102 SETTING IS 160.0` from being added because it acts on the same link. The result is that the valve does become open but uses whatever setting it was originally assigned.

I think that the action ordering used in 2.2 is more natural and again, the order only matters if the same link has more than one action clause. If one understands that assigning a setting to a valve or pump automatically causes it to become "open" at whatever the setting is, then there is no need that I can see for ever using more than one action clause for a given link in the `THEN `and `ELSE `portions of a rule.

**Comment by jamesuber** [comment]
Hey @sm-rana, as the person who originally wrote that particular rule set, I'll agree with Lew on this issue. We should fix this by removing the OPEN clause and rely on just the valve setting.

Having said that, doing a little clean up on the issue of pipe and valve control could be a useful future endeavor (in a later version of Epanet, I emphasize, and likely one that involves some considerable restructuring).

This is an area where a lot of confusion can and does occur. Even relatively seasoned modelers can lack confidence about how Open/Closed/Active status combines with changing the setting of a valve of a particular type. 

This is sometimes complicated, in Epanet, by allowing ourselves to change an initial pipe status in the Pipes section, a valve setting in the Valves section, and both pipe and valve statuses and settings  in the Status section. This can lead to lost time and needless confusion - a combination of ignorance of how the different input sections interact, and the annoyance (and error-prone-ness) of having to do cross checking in different places. Has certainly happened to me, and others that I know.

Personally, I'd prefer we had valve objects that only allowed the modeler to specify what you can actually do to them. And Epanet should support and require a minor loss versus % open curve for every TCV that a modeler is going to try to control. Then we could completely get rid of the statuses from the user perspective, and relegate them to the internals where they probably belong. So then a user can specify only settings - e.g. a pressure setting of a PRV or a percent open for a TCV, and of course a pressure of 1000 psi would fully open that valve, as would a percent open of 100%. Combined with only allowing such settings in the valves section, things would be much clearer and less error-prone, IMHO.

I'd make an exception for pipes being open/closed, cause there's a lot of practical reasons one wants to have that capability, but I'd keep that only in the Pipes section and get rid of the Status section completely (or vice-versa, not allow settings/statuses in Valves/Pipes, and put them only in the Status section.

**Comment by kobusvanzyl** [comment]
Jim, I get your point but it's important in some modelling applications to be able to disable a valve. For instance, in an optimisation exercise where the optimal location of a PRV is determined, it makes sense to add PRVs to all potential locations and then active one at a time. Disabling them with a large setting will work, but can cause confusion itself when a too low value is inadvertently chosen. 

Since other link types (pipes and pumps) have on/off settings, wouldn't it make sense to have the same for valves? Perhaps using a more accurate term for the status will help clarify things.

**Comment by jamesuber** [comment]
Thanks @kobusvanzyl - I wouldn't be surprised if it was use cases like yours that motivated the original design. I can understand these are certainly important use cases to handle with the simulator without doing silly things (like writing out a new input file in code and then reading it back in).

I hadn't considered this before, but now that the dev team has implemented a network creation API (that I haven't looked at), might this use case more properly be assigned to that capability? In other words, the GA/objective function evaluator knows the set of possible PRV locations (pipes), and when one is selected to be "activated", a new junction and valve is added, and the pipe re-routed through the new junction -- would that work for this application? I see there may be some performance changes cause doing the above will take more time than just changing statuses, but then again we're not littering the simulation with PRVs that aren't actually there. And if the new API wouldn't handle this use-case (I suspect it would), then maybe it should.

I think it's interesting to "re-think" these use cases in light of this new API capability? It's a significant addition to what we've had.

**Comment by kobusvanzyl** [comment]
Thanks @jamesuber - I agree about the importance of re-thinking things. 

Adding and removing components with the API will be more efficient than modifying and re-reading the input file, but it won't get rid of the overheads associated with sorting the links (to ensure the smallest possible sparse matrix) and then setting up the memory structures for the solver from scratch. Thus when a modeller knows that he/she will be testing different link configurations, it will  (IMHO) always be more efficient to define all possible links at the start and then deactivate the ones not needed using the API. 

I think it makes sense to have the ability for a user to activate or deactivate any link in the system. A user may for instance want to run a few quick what-if scenarios by deactivating certain links in the user interface or API and we may not want to run the solver setup for each case. On balance I think the ability to deactivate links has more benefits than drawbacks. 

To go off on a tangent: pipes are closed EPANET by giving them a very small diameter (i.e. high resistance) and thus no computational efficiency savings are made. I remember checking this at one point and noticing that once the solver matrix for a larger system is defined, it is possible to solve any sub-set of this matrix without requiring a change to the matrix structure. If I'm right it may be possible to improve the efficiency by simply ignoring the parts of the solution matrix that represent the closed links, rather than recalculating the whole set. This process will have overheads itself, but it may be worth exploring.
