### ISSUE TITLE
Should the Toolkit keep track of Comments, Tags, and link Vertices?

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#419]
The use case I've been focusing on lately is using the Toolkit to manage all network data in a graphical User Interface where objects are dynamically being created, edited and deleted. Ideally the UI would rely solely on the Toolkit to keep track of all data elements without devoting any of its own code for this purpose.

The current set of Toolkit functions does not dynamically manage Comments attached to network objects, Tags assigned to nodes and links, and Vertex coordinates used to represent curved links as none of these is needed to perform a network simulation. This forces the UI to keep track of these items separately, which defeats the purpose of relying solely on the Toolkit for database management. (E.g., the UI would have to duplicate the dynamic list of nodes and links maintained by the Toolkit, with Comment, Tag and Vertex attributes attached to them.)

Should the Toolkit keep track of Comments, Tags, and Vertices? This would require adding six more getter/setter functions to the Toolkit's already large number of functions but would allow it to fulfill one it's intended uses.

**Comment by eladsal** [comment]
In my mind, all data stored in the INP file by the GUI should be accessible by the toolkit's APIs. If I'm not mistaken, comments for Nodes and Links are read and written by the toolkit.

**Comment by samhatchett** [comment]
for a simple GUI this is fine - but for a more complex application that perhaps interacts with GIS or other data sources, the `inp` file is not the home (either source or destination) for this data. I would just re-emphasize my soapbox position which is to decompose the problem domain a bit further. This was the motivation behind the separate binary file I/O library - to separate concerns and make it easier to build more complex things.

**Comment by michaeltryby** [comment]
@LRossman if the engine doesn't need it, the engine shouldn't manage it. It's fine for the UI to have it's own smaller data model to manage it's data and coordinate with the engine's data.

**Comment by michaeltryby** [comment]
I think one of the reasons this is an issue is because the input file parser and writer are fused to the solver's data model. If we decoupled them, we would have more flexibility when addressing issues like this. So I guess I agree with @samhatchett.

**Comment by LRossman** [comment]
Folks, I'm not necessarily talking about an input file. The Toolkit can now be used to build and manage a network database regardless of whether the data come from an INP file, a shape file or direct user input. If comments, tags, and vertices are needed by an app then why require that it use a separate database to manage these instead of using the one provided by the Toolkit.

For example, if we were to re-write the EPANET GUI using the Toolkit as its database we would have to create a complementary database of nodes and links kept in synch with those in the Toolkit just to have access to tags and vertices. Think of how much simpler it would be if we could replace all of the code required to do that with a couple of function calls (e.g., `EN_gettag, EN_settag, EN_getvertices, EN_setvertices`).

**Comment by samhatchett** [comment]
a more complex app will have to have this extra data model anyway. no way is epanet going to anticipate future application needs and provide the preferred API for interacting with future attributes. pipe age? material? soil conditions? criticality? date of installation? nope - the toolkit is for hydraulics.

**Comment by eladsal** [comment]
So many people use a combination of GUI-DLL-INP. I'm not suggesting that we add more data to the INP, just have the toolkit read\write the **current** INP file with all of it's components.

**Comment by michaeltryby** [comment]
Separation of concerns!

**Comment by LRossman** [comment]
Since the response has been a resounding NO to my question I am closing this issue.

**Comment by samhatchett** [comment]
I feel that interpreting this as a "resounding no" misses an opportunity.

Certainly I would **not** say that managing vertices, comments, and the like is outside the concern of this OSS project. These features are managed in the `inp` file and exposed in the GUI as being related to the network elements. While they are not needed for hyd/wq analysis, they are legacy supported features. 

I fully support the idea of helping to manage that data, given that it's usually found in the `inp` file, but what I'm trying to work towards is that an elegant solution looks like decomposing the toolkit into simpler pieces (thus separating concerns).

Consider a hydraulic/wq analysis data model - with no extra data burdening it (comments, coordinates, vertices, perhaps even names[?] are just left out since they are not the concern of the solver/evolver). Outside of that functional unit is a layer that manages the `inp`-style data model with associated attributes mentioned in this thread. And yet another layer that handles [de]serialization of that data - to `inp` format, `JSON`, `XML`, whatever.

A really great question is how to best design the interfaces between those pieces, and thus facilitate managing (synchronizing or coordinating) the data held in each layer. Not duplicating any data, but providing access and proper encapsulation.

**Comment by eladsal** [comment]
> I feel that interpreting this as a "resounding no" misses an opportunity.

I "voted" **Yes**
