### ISSUE TITLE
Return Index of the new object added (ENadd_)

### ISSUE THREAD

**Issue by Mariosmsk** [OpenWaterAnalytics/EPANET#432]
`ENaddnode`, `ENaddlink`, `ENaddcurve`, `ENaddpattern`

Only `ENaddcontrol `it's ok.

What do you think?

**Comment by LRossman** [comment]
Makes sense but it will break compatibility with v.2.1's `ENaddcurve` and` ENaddpattern.`

**Comment by LRossman** [comment]
Thinking more about this, I believe that returning the index of a newly added node is a very good idea since junction nodes are not added to the end of the `Node `array but instead are inserted just before the first tank node in the array. And to maintain some consistency in function arguments, the index should also be returned when a new link is added (even though links are always added to the end of the `Link `array). So both `ENaddnode` and `ENaddlink` should have their argument list expanded, but `ENaddcurve` and `ENaddpattern` should not be altered so as to maintain backward compatibility.

**Comment by michaeltryby** [comment]
Since indexes are an implementation detail, we could make the API easier to use by eliminating them and exclusively using ID strings instead. See Issue #91.

**Comment by samhatchett** [comment]
I realize this issue is closed. But I just tried to rebuild the `epanet_python` wrapper, and behold it is broken because of this change. 

For now I will pull a version of this library that precedes the index-returning modification.

Also I totally understand that via "lazy consensus", this change made its way into `dev`, but I would like to retroactively vote against returning indices. If a client application is mutating the network and _also_ keeping track of toolkit-owned indices, this sounds like a recipe for disaster. If anyone would consider supporting the move to revert #461, please speak up.

**Comment by michaeltryby** [comment]
@samhatchett one of the reasons I created `epanet_py.h` and `epanet_py.c` is so we would have the flexibility to create a better API on the python side while not impacting the the standard Toolkit API that we all know and love despite how clunky it is. :smile:  

We don't need to expose the index being returned or maybe there is something clever we can do on the python side to manage indexes. I don't have any specific ideas, but it might be worth thinking out of the C API box! :bulb:

**Comment by samhatchett** [comment]
2 thoughts:

- the clunky API is being extended here, and my beef is not with the standard API that we know and love, but with a mod of one of the new API functions
- The PR mentioned (#461) does modify `epanet_py.c` in concert with the rest of the API changes, without a commensurate change to `toolkit.i` in the other repo (see referenced commits)

https://github.com/OpenWaterAnalytics/EPANET/blob/dev/src/epanet_py.c#L329
https://github.com/OpenWaterAnalytics/epanet-python/blob/dev/epanet_python/toolkit/epanet/toolkit/toolkit.i#L173

If anything then, I would request confirmation that it doesn't make sense for the API change to be applied to `epanet_py.c`. I would be happy to PR a remedy.

**Comment by michaeltryby** [comment]
Well perhaps the original author of #461 can help you then, since I don't know what his intention was.

**Comment by LRossman** [comment]
@samhatchett would it help if in _epanet_py.c_ `node_add()` was re-written as:
```
int EXPORT_PY_API node_add(Handle ph, char *id, EN_NodeType nodeType)
{
    int index = 0;
    handle_t *pr = (handle_t *)ph;
    return set_error(pr->error, EN_addnode(pr->project, id, nodeType, &index));
}
```
with something similar for `link_add()`, and with complementary changes made to the function declarations in _epanet_py.h_.
