### ISSUE TITLE
Build scripts documentation

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#480]
Hi,
I just started a Wiki page for the build scripts, it might be more easier to collaborate there and then, if needed, include it in the release notes:
[https://github.com/OpenWaterAnalytics/EPANET/wiki/Building-the-EPANET-library-and-executable-files](https://github.com/OpenWaterAnalytics/EPANET/wiki/Building-the-EPANET-library-and-executable-files)

@samhatchett, @LRossman  Can you please help with the wording and information about Linux and Mac builds.

@Mariosmsk, @eldemet you had some videos to demonstrate the build process, would you like to include them?

**Comment by eldemet** [comment]
@eladsal sure! We should make the compilation process as easy to follow as possible!

**Comment by LRossman** [comment]
This comment may be more appropriate as a separate issue, but I think there are other topics in the wiki that need updating:

1. "What's new in version 2.1" should be updated to 2.2 (can we simply use the existing ReleaseNotes2_2 file?)
2. The contents of the "API Documentation" link in the footer should be replaced by the doxygen-compiled v2.2 doc files.
3. Similarly, the topics listed on the Main Page should be updated to be in synch with the contents of the "API Documentation".

I have attached the doxygen compiled version of the 2.2 doc files for everyone's review (unzip the file and double click on _index.html_ to view it). I can try to work on items 1 and 3 but I have no idea how to implement item 2.
[epanet2_2_doc.zip](https://github.com/OpenWaterAnalytics/EPANET/files/3163448/epanet2_2_doc.zip)

**Comment by samhatchett** [comment]
Great, thanks for the notes. You may already know - the doxygen output is all tracked in the [`gh-pages`](https://github.com/OpenWaterAnalytics/EPANET/tree/gh-pages) branch, so feel free to commit the new dox to that branch when appropriate. I think we discussed at some point automating that part too...

**Comment by eladsal** [comment]
@LRossman I think that a instead of updating the "What's new in 2.1" it is better to make a new one for 2.2. The doxygen files are hosted on owa website:
http://wateranalytics.org/EPANET/

**Comment by samhatchett** [comment]
the doxygen files are hosted on GitHub - with the domain URL pointing to it. So if you checkout the `gh-pages` branch, remove all the files except `.nojekyll`, and copy in the new docs and commit, the online documentation will be available via the URL

**Comment by LRossman** [comment]
Thanks for the info. I will wait until just before v2.2 is launched to replace the files in the `gh-pages` branch. In the meantime I can work on the other wiki pages.

**Comment by eladsal** [comment]
@LRossman what do you plan to add to the wiki? when I started the wiki it was decided that the main documentation would be in doxygen so the wiki pages were not completed nor was the doxygen docs. I started the build scripts page on the wiki just to collaborate with the thinking that when ready it will be moved somewhere else (maybe doxygen).

**Comment by eldemet** [comment]
@eladsal 

1. Of course initially the wiki was a directly transcription of the original EPANET help files. This was a huge effort, but maybe now it has served its purpose and we should remove those pages. doxygen provides a better interactive experience, but requires some extra effort to maintain. 

2. I couldn't find a link to `http://wateranalytics.org/EPANET/` in the readme, do we give it somewhere else? If not, perhaps we should.

3. I think we should keep the help files for different versions. e.g. `http://wateranalytics.org/EPANETv2.1/` and `http://wateranalytics.org/OWA-EPANETv2.2/` or something like that, as someone may be using an older version and may need to find something there. We need to keep a version these online I believe.

**Comment by eladsal** [comment]
@eldemet if my comment about the wiki was understood in a way that I would like to keep updating it then I'll clearly say that I don't - that ship has sailed. It's doxygen time...

**Comment by LRossman** [comment]
I was only going to add a "What's new in version 2.2" to the wiki and edit some of the content in the "help" topics linked to the Home page. However, I agree with the above comments that the latter material will appear in the new "API Documentation" pages (see the zip file I attached to my earlier comment). Thus maybe the current Home page should just be a paragraph or two, like what appears in the Overview section of the _main.dox_ file in the `\doc` folder of `dev`, and all of the sub-topics linked to Home can be removed.

The suggestion about keeping older help files has me confused since the material in the new 2.2 API doc is entirely consistent (i.e., backward compatible) with v2.1 (plus it's organized and formatted more like the original EPANET Toolkit help file). If it would help, we could add a short tag to each function's description indicating if it was introduced in v2.1 or v2.2. But bottom line I would vote for just keeping one set of API Documentation files hosted on GitHubs' gh-pages branch.

**Comment by eldemet** [comment]
@LRossman, I understand what you are saying. What I had in mind was closer to the way QGIS handles it: https://qgis.org/api/ (they also use doxygen). There, you can see the documentation from previous versions (e.g., https://qgis.org/api/3.2/, https://qgis.org/api/3.0/).  I just considered the case where someone could be looking for the notes of a specific version (e.g. 2.1, and how it was working), for any reason.

**Comment by LRossman** [comment]
I just replaced the contents of the main wiki page, saving the old version in a new page in case we don't like this new one. As far as removing wiki pages, I suggest that we delete all of the pages that describe the toolkit functions (since those just repeat material in the doxygen docs) but keep the pages that describe the format of an EPANET input file (since those are not included in the doxygen docs). Or if that is still too much to keep on the wiki then we delete those too and just refer readers to the EPANET Users Manual. Any thoughts?

**Comment by samhatchett** [comment]
I think the new wiki landing-page is great! As for documentation, we set up the `gh-pages` system because it was easy - but we could move to a versioned format just by adding subdirectories in that hierarchy. Or can move to readthedocs, which supports versioned documentation already.
