### ISSUE TITLE
To do list for v2.2

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#488]
- [x] Close v2.2 [issues](https://github.com/OpenWaterAnalytics/EPANET/milestone/4).
- [x] Update [README.md](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/README.md) including the build badges to point to the master branch.
- [x] Build Windows\Mac\Linux DLL\EXE.
- [x] merge `dev` into `master`
- [x] Update authors list.
- [x] Update `gh-pages` from doxygen.
- [ ] Include a PDF version of doxygen?
- [x] Go over all issues to see if some may be closed
- [x] Make a release for the test files and update the `mater` branch there. 

Please add\update this list.

**Comment by samhatchett** [comment]
/ BTW, I updated the authors file to collect all the attributions

**Comment by eladsal** [comment]
Thanks. I think the "mariosmsk" and "Marios Kyriakou" are the same great person @Mariosmsk

**Comment by samhatchett** [comment]
ah, missed that one - thanks.

**Comment by eladsal** [comment]
It seems that the script does not consider co-contributors: https://github.com/OpenWaterAnalytics/EPANET/commit/761199b08e8b885d14a8800256d80890d901af96

**Comment by samhatchett** [comment]
ok, should be good now. there's probably an elegant scripting solution, but I've just edited the file manually for now.

**Comment by LRossman** [comment]
Just a couple of comments on the To Do list:

1. Creating a set of executables for Linux can be problematic, since the binaries will be different for different processors and flavors of Linux. Maybe we just release a tar ball with the minimum number of source code files needed to build a library and executable using `cmake`.
2. I tried building a PDF of the Doxygen output using the instructions provided by Doxygen without success. It seems that something in the LATEX files it generates is incompatible with the PDF writer it uses.

**Comment by eladsal** [comment]
Issue #40 is the last one marked for v2.2

**Comment by eldemet** [comment]
Hi, I've fixed the Doxygen documentation and added the PDF users' guide.

**Comment by eladsal** [comment]
Great @eldemet . I see there is no documentation for the APIs in the PDF and the html files.

**Comment by LRossman** [comment]
I think something went wrong with the HTML generated by @eldemet . Here is how the first page of the output should look:

![image](https://user-images.githubusercontent.com/12769926/69483956-ab4b1b80-0dfb-11ea-9984-fd55e56361cf.png)

I spent a lot of time getting it to look like this so please let's not lose it. I think the files in the `doc `folder are OK since I was able to generate the correctly formatted HTML output shown above by following the simple instruction in the `README.MD` file in the `doc `folder (i.e., in a console window, issue the `doxygen `command while in the `doc `directory).

Also I don't think we should include the generated HTML files the project's source code folder. When we have a release ready they should be placed in the `gh-pages`.

**Comment by eldemet** [comment]
Yes, you are right, sorry, I think I used the wrong branch for the compilation.

**Comment by samhatchett** [comment]
I think, pending the closing of #40 - this is the last issue on 2.2 milestone. I am more than happy to volunteer the merge `dev -> master` and to update the build badges and `gh-pages` branch... everyone OK with that plan? we could conceivably tag 2.2 this week!

**Comment by LRossman** [comment]
I'm ok with the plan. I'm going to merge PR #568 into `dev` right now so that it makes its way into the 2.2 release, and @samhatchett should do the same with #539. Some other less urgent loose ends to address are:

1. Posting binaries to the Release page (with the Windows files including a CHM version of the Toolkit's Doxygen-generated User Guide).
2. Cleaning up the Wiki (remove about 130+ pages, some of which are out of date, that repeat the same material posted to the gh-pages).
3. Maybe clean up the contents of the Projects folder (I'm not sure I understand what this folder is for).

**Comment by eladsal** [comment]
@LRossman can we clean the Wii right after the release so there is no time gap or we lose some information? 
I have just compiled the docs with doxygen, I can't see any of the API's. They are not included in the docs?

**Comment by LRossman** [comment]
@eladsal this sounds like the same issue that @eldemet had earlier when compiling the docs. The resulting `index.html` file should look as shown 5 comments above this one, where the API topics are clearly visible in the TOC panel under _API Reference_ (I expanded this topic in the figure so that you could see that the function descriptions are there). Are you sure that you are working with the current `dev `branch (there should be 22 files in the `doc `folder) and are using a recent version of Doxygen (mine is 1.8.16)?

**Comment by eladsal** [comment]
Yes, it is the current `dev` branch with the 22 files. I have downloaded Doxygen today, it is 1.8.16.
Here is the Doxygen log file: [doxygen_log.txt](https://github.com/OpenWaterAnalytics/EPANET/files/3932274/doxygen_log.txt)
BTW, I'm using the Windows GUI of Doxygen.

**Comment by eladsal** [comment]
@LRossman and @eldemet just tried to run Doxygen from the command line and it worked fine! Now I have all the APIs in place.

**Comment by LRossman** [comment]
@eladsal good to know. The instructions for building the HTML doc pages in the doc folder's  `readme.md` file say to run Doxygen from the command line.

Regarding your other question, I will volunteer to clean up the Wiki pages once the v2.2 release is made.

**Comment by samhatchett** [comment]
I have created the 2.2 PR - would be great to get a sign-off from each of you. 

I did update the dox to the 2.2 version -> http://wateranalytics.org/EPANET/index.html

... and the binaries can be added to the release after the merge/tag. I will volunteer to build the Mac binary bundle (dylib and CLI).

**Comment by eladsal** [comment]
@LRossman do you remember how to pack the test networks (last item on the above todo list)?

**Comment by eladsal** [comment]
The new compiled Windows DLL and EXE if someone wants to test them
https://www.dropbox.com/sh/nbt2zqjdico42n7/AAAGRCsELhdHUx48FXcjQ-qAa?dl=0

**Comment by LRossman** [comment]
I have exercised @eladsal 's 64-bit Windows DLL in my LEPANET GUI and everything looks good.

One minor issue I noticed is that when a new tank node is created it's default area is set to 1 ft. Unlike some of the other element properties, like for pipes, which were assigned reasonable default values, this one is totally unrealistic. I'm not sure it merits making a change at this point in time.

**Comment by LRossman** [comment]
@eladsal I'm not sure what you mean by "pack test networks". Are you referring to the compressed folders containing the benchmark network input and results files published [here](https://github.com/OpenWaterAnalytics/epanet-example-networks/releases)? If so those folders are up to date. However the contents of the `dev-rolling` branch of that repo should be merged into its `master `branch to keep things in synch.

**Comment by eladsal** [comment]
@LRossman yes, this is what I meant.

**Comment by eladsal** [comment]
@samhatchett can you please update `master` on https://github.com/OpenWaterAnalytics/epanet-example-networks and maybe also release a version?

**Comment by samhatchett** [comment]
is there some naming convention here? I can't really discern.

**Comment by samhatchett** [comment]
I will just tag it with the patch incremented and remove the "dev" suffix

**Comment by eladsal** [comment]
Maybe my suggestions was wrong. It might break the testing of the toolkit as it looks for the latest  release with all the output files of the tests networks. Anyone knows?

**Comment by eladsal** [comment]
Its about time we close this issue...
