### ISSUE TITLE
Pumps with Speed Pattern takes precedence over controls

### ISSUE THREAD

**Issue by allenmlowe** [OpenWaterAnalytics/EPANET#541]
Speed patterns are used in pumps to simulate variable speed pumps by changing their speed settings. 

However, controls such as shutting of the pump when the tank is full is ignored because the pump still try to continue to operate if the setting is not 0.

[ Pump Pattern_Controls Test.zip](https://github.com/OpenWaterAnalytics/EPANET/files/3711018/Pump.Pattern_Controls.Test.zip)

![curved_pump_rule-based_no_pattern](https://user-images.githubusercontent.com/39788972/66547316-88c5b180-eb71-11e9-9b25-654ffaf78b89.jpg)
![curved_pump_rule-based_with_pattern](https://user-images.githubusercontent.com/39788972/66547329-911dec80-eb71-11e9-94fa-e1054ef51b60.jpg)

**Comment by LRossman** [comment]
In the current code (v2.0 - v2.2), at a given point in time just before the next hydraulic solution is computed, a pump's speed setting or status is determined first by any rule-based controls, then by its assigned speed pattern, and finally by any simple controls that apply to it.

In the example that was provided, the pump P-1 was assigned a constant speed pattern of 1, a simple control that turned it off at hour 6 and rule-based controls that turned it off when tank T-1 reached 14.9 m. As seen in the second plot above, the simple control overrides the speed pattern at hour 6 but after that the pattern kicks in again keeping the pump turned on.

What's not shown is that since the speed pattern is applied AFTER the tank-level rule, the latter is never enforced and the tank's level hits it maximum of 15 m instead of 14.9 and the pump never shuts off. If the tank-level rule was instead expressed as a simple control, then the latter would be implemented after the pattern setting, causing the pump to shut down whenever the 14.9 m level was reached.

So the issue is that the rule-based controls are being overridden by the pump's speed pattern thus failing to keep the tank level within its desired bounds. When I modified a new branch of the v2.2 code to execute controls in the order of first speed pattern, then simple controls, and then rule-based controls, I got the following results for this example using a 6-minute reporting step (so that pump shutdowns within hourly intervals could be seen):
![image](https://user-images.githubusercontent.com/12769926/66837022-554ba400-ef30-11e9-933c-090d736d80c8.png)
![image](https://user-images.githubusercontent.com/12769926/66837038-5ed50c00-ef30-11e9-8a7a-c8a240de6dee.png)

Should this code change become part of v2.2 (it could produce different results for some models when compared with v2.0) or be put off until some future update?
