### ISSUE TITLE
API needs an EN_getresultindex function 

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#546]
Consider the following use case. A client runs an analysis with results saved to EPANET's binary output file. Then they delete nodes and/or links, or re-arrange them, or add Junction nodes (which changes the indices of Tanks and Reservoirs). Before making a new analysis they wish to retrieve results from the output file. Because of re-indexing, some results in the file will no longer belong to the elements they were originally computed for. Such a scenario can commonly occur when the API is used to drive a GUI, similar to the legacy EPANET UI, where the most recently computed results can be displayed interactively in a variety of ways (color-coded map, time series plots, tables) even after the network structure has been changed.

The fix is to:

1. Add a new property, `ResultIndex`, to both the `Snode `and `Slink `structs.
2. Initialize `ResultIndex `to 0 when a node/link is first created and when an output file is closed.
3. Assign the position of each node and link in the network's `Node `and `Link `arrays to its respective `ResultIndex `property when an output file is opened.
4. Add a new API function named `EN_getresultindex()` that retrieves the `ResultIndex `for a particular node or link.

**Comment by eladsal** [comment]
@LRossman not sure I understand the use case, do you have an example?

**Comment by samhatchett** [comment]
I think I understand - but this adds complexity without a very compelling story behind its motivation. The downside I see is that this more tightly couples the toolkit to the binary file generation functionality, which is a "separation of concerns" issue.

I might suggest that  there should be an invalidation mechanism so that an API caller can't just use an out-of-date results file for loading results through the toolkit (as in to run a WQ analysis), or that the enclosing context (managed by the GUI) should be responsible for loading/visualizing old results and mapping them to updated element indices. I would think that the output file parser would be a handy tool for that purpose.

I guess the point is the same as @eladsal - I'm looking for a beefier description of what this is really _for_. Do you have a case where "the API is used to drive a GUI, similar to the legacy EPANET UI"? If so, this problem seems more suited to design-work on that end, rather than in the toolkit. Really looking forward to hearing your thoughts.

**Comment by LRossman** [comment]
Let me explain further. I've been working on a project that duplicates the functionality of the legacy GUI but instead of maintaining a separate network database within the GUI code and then writing that data to an INP file whenever an analysis is made (as the current EPANET Delphi GUI does) it uses toolkit functions to keep just a single copy of the data (in the toolkit's Project struct). So far this arrangement is working fine (see screenshot below) except that if a user starts changing the network structure after a run is made the results in the current output file may be out of alignment with how the network elements now appear in the Project's Node and Link structs. If a user then wants to see a different view of the network's results they will be shown incorrectly. In the current EPANET GUI this type of user action presents no such problem.

To resolve this issue the GUI developer would have to manage a duplicate database of node and link information within its code which has to be synchronized with whatever changes (element additions/deletions/ID changes) are made as the user edits a network (which the GUI implements via API calls). This would be true even if the GUI were using some other method, besides an EPANET output file, to store analysis results. The output file parser offers no help here since it indexes results in the same order as they were written to the output file.

All that my suggestion is doing is storing the index of a node or link, within the node or link's struct, right before a new analysis is made so that afterwards it is easy to locate the computed results for the node/link (using a new `EN_getresultindex` function) even if its position in the Project's array of nodes/links has changed due to network editing. It only adds one new function and about 15 new lines of code to the toolkit while saving the GUI developer from having to write a bunch of duplicative code themselves.

![image](https://user-images.githubusercontent.com/12769926/66975162-9eecd980-f06b-11e9-8d43-a29d507c4ff0.png)

**Comment by samhatchett** [comment]
yep, I'm good with this too. Thanks @LRossman for the explainer.
