### ISSUE TITLE
Energy Report Inconsistent

### ISSUE THREAD

**Issue by allenmlowe** [OpenWaterAnalytics/EPANET#577]
This is a sample network of similar configuration of pumps and tanks which should give the same energy results but give inconsistent results. The sample inp file does not run when hydraulic time step is less than 1:00.
[Tanks_Series.zip](https://github.com/OpenWaterAnalytics/EPANET/files/4034868/Tanks_Series.zip)
 
![Tank_Series](https://user-images.githubusercontent.com/39788972/71972121-066b8d00-3247-11ea-84d7-a28fd850ce46.jpg)
 
![Tank_Series @  15 minutes](https://user-images.githubusercontent.com/39788972/71972165-197e5d00-3247-11ea-8e55-9c401a00f173.jpg)

**Comment by LRossman** [comment]
First off, the model runs OK with time steps under an hour under the v2.2 engine so I suggest that future bug reports be with respect to that version and not older ones. (The older v2.0.012 GUI will work with the new v2.2 engine DLL).

Using a 15 minute hydraulic time step the model still shows inconsistent energy consumption by the pumps between each configuration. This is due to each tank becoming full in less than an hour. So as each tank supplies demand to the the end junction we would like the pumps to supply that same amount of flow to the tank so that it remains full. But since EPANET doesn't have an automatic pump speed controller pegged to flow rate, it can only do one of the following:

1. Simulate an altitude valve that closes a link trying to send flow into a full tank by internally setting its flow resistance to a very high value (which is what the original model discussed here does).
2. Allow the tanks to overflow (which can now be modeled in v2.2)
3. Apply a set of on/off controls to the pumps that keep the tank levels within a reasonable range.

Using Options 2 and 3 (with Tank limits of 18 to 19 m) produces consistent energy consumption between the four configurations in contrast to Option 1. The head loss (negative head gain) for each option's pumps are shown below:
![image](https://user-images.githubusercontent.com/12769926/72014497-f85d4280-322d-11ea-96aa-4113e8b0bd7a.png)
![image](https://user-images.githubusercontent.com/12769926/72014547-16c33e00-322e-11ea-8321-121f8641f4ef.png)
![image](https://user-images.githubusercontent.com/12769926/72014576-22166980-322e-11ea-9ef6-952aa2d54a73.png)

Under Option 1, the arrangement of the pipe/pump combination on the tank's inflow side influences the heads developed by the pumps and results in unequal pump heads even though the flows are the same. Thus the energy usage, proportional to head x flow, will be different for the two arrangements.

**Comment by allenmlowe** [comment]
Thank you Lew for a detailed explanation.  I was using the v2.0.012 GUI with the latest v2.2 engine DLL released a month ago. Probably that release was having a problem with time steps under an hour.

**Comment by LRossman** [comment]
@allenmlowe, yes the update made on 12/5/2019 in response to one of your earlier bug reports (see issue #528 and PR #568) likely fixed the problem you were having using shorter time steps.

**Comment by allenmlowe** [comment]
I noticed that when a pump is directly connected to a tank, it's energy report is different from what is expected. After analyzing the source, I did some modifications. I removed the // Compute pumping energy from nexthyd function and inserted in tanklevels function. It seem to correct the issue but I don't know if this is the right solution since it might break some other routines.

void  tanklevels(Project *pr, long tstep)
/*
**----------------------------------------------------------------
**  Input:   tstep = current time step
**  Output:  none
**  Purpose: computes new water levels in tanks after current
**           time step
**----------------------------------------------------------------
*/
{
    Network *net = &pr->network;
    Hydraul *hyd = &pr->hydraul;

    int    i, n;
    double dv;

    // Compute pumping energy
    Times   *time = &pr->times;
    if (time->Dur == 0) addenergy(pr,0);
    else if (time->Htime < time->Dur) addenergy(pr,tstep);

    for (i = 1; i <= net->Ntanks; i++)
    {
        Stank *tank = &net->Tank[i];
...
[Tank_Series_CFS.zip](https://github.com/OpenWaterAnalytics/EPANET/files/5249585/Tank_Series_CFS.zip)

![Tank_Series_Energy](https://user-images.githubusercontent.com/39788972/93664730-a8fd3080-faa3-11ea-9e43-c82064746115.jpg)
![Tank_Series_Corrected](https://user-images.githubusercontent.com/39788972/93664801-190bb680-faa4-11ea-9d1a-e26c32929f29.jpg)

**Comment by LRossman** [comment]
@allenmlowe excellent catch. What's happening is that the `nexthyd `function first calls the `timestep `function that determines the length of the next time step to take after the solution for the current time has been found. This function is also calling `tanklevels `to update the tank levels over the resulting time step. After `timestep `is called, `addenergy `is called to compute the energy used by the pumps over the time step. But instead of using the tank levels at the start of the period for which the current hydraulic solution applies, it's using the updated levels in its calculation instead. 

I don't think that moving the call to `addenergy `to the top of `tanklevels `is the way to resolve this for two reasons:
1. `timestep `and thus `tanklevels `is not called for a single period (snapshot) analysis. Thus no energy usage would be computed for this type of simulation.
2. When rule-based controls are involved, the `tanklevels `function is called for every `RuleStep `sub-interval (the default being 6 minutes) where rules are being checked. Thus the tank heads used in `addenergy `would be changing over every sub-interval giving a different total energy if no rules applied compared to the case where no rule-based controls were ever specified.

There's another problem with calling `addenergy `after `timestep`. When the latter function checks for the shortest time for a rule to fire within the currently found next time step it will update the status or speed setting of a pump if it appears in a rule that gets applied. When `addenergy `is called after this, it is basing its pump energy calculation on the new status/setting for the next period instead of the one for the current period.

It seems that the best solution to these problems is to move the `getenergy `function, which computes the instantaneous kilowatt power and efficiency of a pump, out of `addenergy `and call it in `nexthyd `before `timestep`. The values it computes would be stored in two new fields of a pump's `Senergy `struct. Then the call to `addenergy`, which requires knowledge of the next time step to take, would remain where it is but its body would be modified to no longer call `getenergy `but instead use the power and efficiency values saved to a pump's `Senergy `struct.

**Comment by allenmlowe** [comment]
Thanks @LRossman for the detailed explanation.

**Comment by allenmlowe** [comment]
The modification to correct this issue seems to have an effect on the energy report for pumps that are altered by controls or are not 100% utilized. The before and after energy report for this particular network is shown below. I think the correct average efficiency of pump2 should be 72% and not 62.32 after the modification.
![Before Modification](https://user-images.githubusercontent.com/39788972/101593542-0e214c00-3a2b-11eb-9425-f55bd86ce33e.jpg)
![After Modification](https://user-images.githubusercontent.com/39788972/101593549-124d6980-3a2b-11eb-9a1c-52d2a340299d.jpg)
[Ex4-1PA.zip](https://github.com/OpenWaterAnalytics/EPANET/files/5663911/Ex4-1PA.zip)

**Comment by LRossman** [comment]
@allenmlowe there is a bug in both the original (v2.2) and the updated energy usage routine that incorrectly adds to a closed pump's time on-line the time step between the current solution time and the time when a rule-based control re-opens it. PR #619 for the `fix_energy_usage` branch fixes the problem. The correct energy usage table for your example looks as follows:

![image](https://user-images.githubusercontent.com/12769926/101710904-6fafdd80-3a60-11eb-91bb-7820eed7b00e.png)

Note that the Percent Utilization for PMP-2 is actually 18.78 and not 21.70. This can be verified by viewing the Status Report which shows that PMP-2 is open between time 0:00:00 and 13:42:00, closed until 17:15:02, after which it is open until hour 24. Thus the time it is open is 16,167 seconds which when divided by 24*3600 gives a percent utilization of 18.7.
