### ISSUE TITLE
Winodws Temporary File Name function choice

### ISSUE THREAD

**Issue by dly9000** [OpenWaterAnalytics/EPANET#581]
What is the reason behind using `_tempnam` to generate temporary file names instaed of `tmpnam` or `tmpnam_s`?  Something occured when the switch to the thread safe code base happened where I can no longer run simulations in parrallel within python. I keep getting an error 305 when the last few simulations are executing.  When I run the simulations in serial though, I am able to complete as many as I wish to.

If this is not the right place to bring this up I'm happy to move it to a different forum.

Thank you

**Comment by LRossman** [comment]
`_tempnam` replaced `tmpnam` because it defaults to generating a file name whose path is `\Users\<username>\AppData\Local\Temp`, which is a "safe" location to place temporary files under Windows since the user has guaranteed write access to it. Plus it allows a prefix (`"en"`) to be attached to the file name which makes it easier to locate the file in case a manual cleanup of the aforementioned folder needs to be made (as when the program aborts prematurely for some reason).

However, just as with` tmpnam`, `_tempnam` is not thread safe so it may fail when multiple EPANET projects are being run in parallel. The following code snippet may be a way to avoid this:
```
   // --- use Windows _tempnam function to get a pointer to an
    //     unused file name that begins with "en"
    for (;;)
    {
        strcpy(fname, "");
        name = _tempnam(NULL, "en");
        if (name)
        {
            // --- copy the file name to fname
            if (strlen(name) < MAXFNAME) strncpy(fname, name, MAXFNAME);
            
            // --- free the pointer returned by _tempnam
            free(name);

/////////////////////////////////////
            // -- try to open the file
            FILE *f = fopen(fname, "wb");
            if (f != NULL)
            {
                fclose(f);                
                return;
            }
//////////////////////////////////////
        }
    }
```
Another limitation of `_tempname` and `tmpnam` is that they can only generate a maximum of 32,767 file names. If you are running some kind of genetic algorithm or Monte Carlo simulation where you keep calling  `EN_createproject` at every trial then it is possible that you could exceed this limit. A better strategy is to call `EN_createproject` just once for each thread and then use the toolkit functions to modify the network data and make runs in each thread for each of your trials.

**Comment by dly9000** [comment]
Finally had some time to try and incorperate this into the source code. It builds on it's own with no issuses and builds within the owa-epanet swig wrapper.  I have been successfully running O(10^5+) simulations without any problems with the INT_MAX limit of 32,767 through the python wrapper.  the way I am running my parrallel sims is via the multiproccess module, so I do not have thread safety issuses.

**Comment by dly9000** [comment]
I tried running 1,000,000 simulations but only made it to 975,000 before encountering error 305
