### ISSUE TITLE
ctime is not threadsafe

### ISSUE THREAD

**Issue by mcneish1** [OpenWaterAnalytics/EPANET#592]
test_reent.cpp runs two copies of EPANET concurrently. Most of EPANET's state is held in `Project`s, so [ThreadSanitizer](https://clang.llvm.org/docs/ThreadSanitizer.html) is almost clean, however `ctime` is not thread-safe (https://linux.die.net/man/3/ctime, see Notes) and report.c calls `ctime` a couple times (below). ThreadSanitizer issues warnings about potential race conditions for these calls.

https://github.com/OpenWaterAnalytics/EPANET/blob/d8ba9b11c5b805225d3dced7b72f5a7da8e4b42f/src/report.c#L203
https://github.com/OpenWaterAnalytics/EPANET/blob/d8ba9b11c5b805225d3dced7b72f5a7da8e4b42f/src/report.c#L1442

POSIX has `ctime_r` for this purpose, and Windows has `ctime_s`. (`ctime_s` was additionally standardized in C11.) Alternatively, a mutex for this purpose could be passed into `EN_createproject`.

I would submit a PR for this, however I'm not sure which option makes the most sense, and I'd rather not get into testing for the presence of `ctime_r` / `ctime_s` vs using `pthread` or `CreateMutex` until I do.

**Comment by LRossman** [comment]
`ctime `has two uses in `report.c`. One is to write a time stamp at the top of the text report that EPANET produces. The other is to write the start and end date/times for an analysis (i.e., the time spent between calling `EN_open` and `EN_close`). I'm not sure what implications lack of thread safety has when `ctime `is called. Since it's basically reading from a static system memory location, which could be overwritten by a call from another project thread, it seems the worse that could happen is that a slightly inaccurate date/time is returned. If this is the case then I don't think it's worth bothering about.

If one thinks it is important enough to address then I suggest rather than messing around with different C standard compliant functions we could do the following:

1. For the report time stamp, delete the line in `writelogo `in `report.c` that calls `ctime `and add the following code to `EN_createproject` 
```
time_t now;
time(&now);
sprintf(p->report.DateStamp, "%s", ctime(&now));
```
2. For the time spent between `EN_open` and `EN_close`, add another variable (perhaps named `RunTime`) to the `Report `struct that holds a `time_t` value returned by calling the thread-safe `time `function . In `EN_open` we add:

```
time_t startTime;
time(&startTime);
p->report.RunTime = startTime;
```
while in `EN_close` we add:
```
time_t endTime;
time(&endTime);
p->report.RunTime = endTime - p->report.RunTime;
```
And then in report.c we write the `pr->report.RunTime` value at the end of the report instead of the start/end date/times as follows:
```
if (rpt->RunTime < 1)
    fprintf(rpt->RptFile, "\n \n Total RunTime : < 1 second");
else    
    fprintf(rpt->RptFile, "\n\n  Total RunTime : %d seconds", rpt->RunTime);
```
