### ISSUE TITLE
Rename x and y variables in EN_setvertices

### ISSUE THREAD

**Issue by csweetapple** [OpenWaterAnalytics/EPANET#600]
See https://github.com/OpenWaterAnalytics/epanet-python/issues/59

**Comment by samhatchett** [comment]
realized I dropped the ball on this one. The suggestion is really just to rename variables in the header declarations, so that SWIG can more reliably map in/out variables. A convention like:

```
int EN_getnodevalue(int index, int code, int *out_value)
```

... would let SWIG know that the last pointer is an output parameter (denoted by `out_*`), as opposed to an input array or something else. 

I see this type of change as being not very disruptive as it only changes the declaration var names, with a high downstream value to auto-wrapped bindings/libraries. I can volunteer to create the PR if everyone is ok with this.

**Comment by LRossman** [comment]
I'm OK with it. I assume you only have to make changes to the epanet2_2.h header file.

**Comment by csweetapple** [comment]
@samhatchett are you able to make this change? I could do with being able to use `setvertices` in owa-epanet once the issue's fixed. Thanks!

**Comment by samhatchett** [comment]
thanks for the bump, @csweetapple - PR has been created. Once that is merged, I'll fold that into the py wrapper. Closing this thread for now - any more convo can happen in #605
