### ISSUE TITLE
Question:  Release 7, dated December, 2019?

### ISSUE THREAD

**Issue by rjanke20** [OpenWaterAnalytics/EPANET#607]
The files for this release (see "EPANET_2_2_WIN_32_64.zip") were updated on June 28, 2020, was there an issue entered documenting the updated files?

**Comment by LRossman** [comment]
No issue was raised on the repo.  Instead a series of emails concerning a network that could be solved under v2.0.12 but became ill-conditioned under the EPA release of v2.2 (but not under the v2.2 build used to run the CI tests) revealed that the release executables posted on the OWA repo were compiled using Visual Studio 2010 instead of Visual Studio 2017. So the release package was updated to use a VS 2017 build.
