### ISSUE TITLE
Unexpected tank volumes

### ISSUE THREAD

**Issue by csweetapple** [OpenWaterAnalytics/EPANET#610]
If the diameter of a tank (with no volume curve) is altered with `EN_setnodevalue`, the new volume(s) appear to be incorrect.

For example, using Net1.inp, which contains the following tank:
```
[TANKS]
;ID              	Elevation   	InitLevel   	MinLevel    	MaxLevel    	Diameter    	MinVol      	VolCurve
 2               	850         	120         	100         	150         	50.5        	0           	                	;
```

Prior to any modifications, `EN_getnodevalue(ph, index, EN_INITVOLUME, &vol);` gives 240355, which is as expected (pi * 120 * 50.5 * 50.5 / 4).

If the diameter is changed to 20, for example, I would expect the initial level (120) to remain the same and the inital volume to change to 37699 (i.e. pi * 120 * 20 * 20 / 4). However, `EN_getnodevalue(ph, index, EN_INITVOLUME, &vol);` gives 206579. Similarly with the maximum volume - I would expect the max level to remain 150, giving a max volume of 47123. However, `EN_getnodevalue(ph, index, EN_MAXVOLUME, &vol);` gives 216004.

There also seems to be some inconsistency with how the min volume is used when creating a tank, which can give some odd volumes - E.g. if I create a new tank and use `EN_settankdata` with the same values as given in the .inp file for tank 2 (including `minvol=0`), `EN_getnodevalue(ph, index_new, EN_INITVOLUME, &vol);` now gives 1909096 instead of 240355. To get the correct initial volume (and min and max volumes), I need to calculate `minvol` from the `minlvl`. Is there a reason `minvol` isn't handled similarly here as it is when supplied via an .inp file (i.e. can be 0 for a cylindrical tank))?

If `minvol == 0`,  `Vmin` is set to:
* `area * minlevel` when creating a network from an .inp file (in input3.c)
* `area * Hmin` when setting tank data using `EN_settankdata`

**Comment by LRossman** [comment]
The following note appears in the source code in the portion of `EN_setnodevalue `where `EN_TANKDIAM `is changed:
```
        // NOTE: For a non-volume curve tank we can't change the Vmin
        //       associated with a Hmin since we don't know the tank's
        //       shape below Hmin. Vmin can always be changed by setting
        //       EN_MINVOLUME in a subsequent function call.
```
So when changing the diameter from 50 to 20, the program keeps using the old `Vmin` value based on a 50 ft diameter, not 20 ft. The picture becomes even less clear if the user had set the Minimum Volume parameter directly, either in the input file or through an API call, to some value not based on the tank's diameter. I can see two possible conventions to follow when changing a tank diameter:

1. Keep the current `Vmin `value (as done now).
2. Assume the tank's shape is cylindrical and compute a new `Vmin `= new area times minimum level (as done when Tank data is read from an input file with the minimum volume field equal to 0). 

In both cases the Toolkit user might have to change `EN_MINVOLUME `after making the diameter change to keep things consistent. Thus I don't think that either alternative is ideal.

The second issue raised by @csweetapple is due to the code in `EN_settankdata `using:
```
Tank[j].Vmin = Tank[j].A * Tank[j].Hmin;
```
when it should be:
```
Tank[j].Vmin = Tank[j].A * (Tank[j].Hmin - elevation);
```

**Comment by csweetapple** [comment]
> 
> The second issue raised by @csweetapple is due to the code in `EN_settankdata `using:
> 
> ```
> Tank[j].Vmin = Tank[j].A * Tank[j].Hmin;
> ```
> 
> when it should be:
> 
> ```
> Tank[j].Vmin = Tank[j].A * (Tank[j].Hmin - elevation);
> ```

The same code appears in `EN_setnodevalue` for `case EN_MINVOLUME` and `EN_TANKDIAM` - presumably this should be updated too.

My comments about volumes updating as expected didn't just refer to `Vmin` (I saw the note in the code about that) - `V0` and `Vmax` have unexpected values too. For example, if I use `EN_setnodedata` to update the diameter and apply a new computed minimum volume but keep all levels the same, the init volume and max volume assigned to the tank are wrong.


However, I think fixing the above error in calculating `Vmin` should sort this out (since `Vmin` is used in the calculation of `V0` and `Vmax`).
