### ISSUE TITLE
Valve settings with values less than zero are considered invalid

### ISSUE THREAD

**Issue by stephen-young** [OpenWaterAnalytics/EPANET#616]
The following lines of code appear to prevent any valve from having a setting value that is less than `0.0`. https://github.com/OpenWaterAnalytics/EPANET/blob/9707075a5a8ad661c2880e108d69551a725aafcf/src/epanet.c#L3888-L3889

Pressures in Epanet appear to all be gauge pressures because a tank with 2 metres of water inside it is evaluated to have 2 m of pressure at the node. In the standalone version of Epanet, valves can have negative settings without issue and I have used PRVs to model a process that brings the pressure bellow atmospheric (i.e. less than 0 metres of pressure). 

There doesn't appear to be a field for inputting what atmospheric pressure is in the standalone Epanet either but shouldn't the actual lower bound for pressure related valves be vacuum (approx. -10 m)? Standalone Epanet also only seems to complain about negative pressures if they are on a demand node and seemingly allows pressures that are bellow a vacuum.

This is causing issues for me when interfacing with Epanet through the Epanet-Matlab-Toolkit because the `.inp` file will have PRVs with settings less than 0. Hydraulic analysis will execute without issue. An error will only be thrown if the original valve setting is attempted to be reapplied (this is necessary if the valve is opened or closed and needs to be reactivated).

**Comment by LRossman** [comment]
I submitted a PR that will allow one to specify a negative pressure setting for a PRV using the Toolkit, so that it maintains consistency with the way an input file is processed. I can't say how soon this update will make it into the Matlab library. In the meantime would it be possible to lower the elevation of the PRV node by the amount of the negative setting so that a setting of 0 could be used instead?
