### ISSUE TITLE
Unit Headloss meaning in EPANET node results

### ISSUE THREAD

**Issue by kalebsm** [OpenWaterAnalytics/EPANET#637]
Hello,
I am trying to figure out the meaning of the unit headloss data in the node reports and how it is calculated. It is going to be feet of headloss unitized by something, but I do not think it is unitized by length of pipe. Any help would be appreciated. Thanks.

![image](https://user-images.githubusercontent.com/56654036/119183106-a0e5fe00-ba41-11eb-8b3c-b61d8983af1b.png)

**Comment by LRossman** [comment]
This question is probably more appropriate for the  [OWA EPANET GUI Users Forum](http://community.wateranalytics.org/c/epanet/gui-users) since it relates to viewing a link result in the EPANET GUI Property Editor while this the repository is for the EPANET engine code. But since you asked, for pipes the reported head loss is feet per 1000 feet (or meters per 1000 meters) of length. For pumps and valves it's the actual head loss in feet (or meters). Please note that the toolkit function `EN_getlinkvalue()` with argument `EN_HEADLOSS `will retrieve the actual, not unit, head loss for pipe links.

**Comment by LaxmiGangwani** [comment]
The toolkit function EN_getlinkvalue() with argument EN_HEADLOSS will retrieve the actual, not unit head loss for pipe links. Please let me know the toolkit function to call unit head loss for pipe as seen in Network Table – Links (EPANET 2.0).
