### ISSUE TITLE
Error running analysis if tank can overflow and has a valid volume curve

### ISSUE THREAD

**Issue by MacPeter65** [OpenWaterAnalytics/EPANET#639]
Hi everyone,

Has someone faced the following error and can offer solution to that? The bug occures in every file I tried, complex and very simple as well. It can be easily reproduced.

I use EPANET Version 2.2. If my model contains a tank with a defined volume curve and overflow is allowed the analysis cannot be run. The error message is the following: Error 206: undefined curve -16s in [TANKS] section.

If I set Can overflow to No the analysis runs correctly. If I set Can overflow back to Yes and I delete the volume curve entry the analysis runs again.

Thanks for the help and answer in advance.

Peter

**Comment by rjanke20** [comment]
This seems to be a bug in the graphical user interface.  Jonathan Burkhardt confirmed that it does not seem to appear in the command line version.

**Comment by MacPeter65** [comment]
Dear Rob,

thank you for your reply.
I'll be honest I'm a little bit confused. I tried what you recommended but I still have an error. But it is different to the one I received before.
If I run analisys in file VolumeCurveCanOverflow.net in the graphical user interface I receive the error I mentioned before. But if I run in the command line version I have Error 223: not enough nodes in network.
If I change can overflow back to no, in the graphical user interface the simulation runs without errors. It is the file VolumeCurveNoOverflow.net. But in the command line version I still have the error 223.
What can it be? Another different bug?

Thank you and regards,

Peter

[NETFiles.zip](https://github.com/OpenWaterAnalytics/EPANET/files/6554642/NETFiles.zip)

**Comment by ucchejbb** [comment]
Peter,

If you export the .net to be .inp, you get the following.
[TANKS]
;ID              	Elevation   	InitLevel   	MinLevel    	MaxLevel    	Diameter    	MinVol      	VolCurve        	Overflow
 20001           	250.750     	0.000       	0.000       	8.250       	10.200      	0           	**-16s**	Yes	;

Note the '-16s' random characters for VolCurve name. If you replace that with your TerfogatGorbe name of your volcurve, the file will run in commandline mode. I've attached the corrected inp file in the attached zip. This is an issue with the GUI saving the file. The Gui resaves a temporary inp file, which is displayed in the error message that EPANET returns when you run it in the GUI.

[TANKS]
;ID              	Elevation   	InitLevel   	MinLevel    	MaxLevel    	Diameter    	MinVol      	VolCurve        	Overflow
 20001           	250.750     	0.000       	0.000       	8.250       	10.200      	0           	TerfogatGorbe 	Yes	;

[VolumeCurveCanOverflow.zip](https://github.com/OpenWaterAnalytics/EPANET/files/6554942/VolumeCurveCanOverflow.zip)

**Comment by LRossman** [comment]
@MacPeter65 the command line version does not recognize the binary .NET input file format that is used by default in the EPANET GUI. It only understands the plain text file format (usually given a .INP extension) that is documented in an appendix of the User's Manual. You can tell the GUI to save your current project in plain text format by issuing the `File | Export | Network `command from the main menu. The `File | Save` or `File | Save As` commands save your project in .NET format. However the `File | Open` command will read either .NET or .INP files.

Regarding the **Can Overflow** bug, as @rjanke20 pointed out it is due to an error in the GUI when it takes your network data and writes it out to a temporary .INP file that is run through the engine (the same as used in the command line version) to produce results. Right now I don't think there is any work-around but it is easy to fix (just one line needs correcting) and hopefully EPA will issue a patch update shortly.

**Comment by MacPeter65** [comment]
Dear everyone,

Thank you very much for the help, actually you've solved my problem.

I'm a new EPANET user. When I receive an unexpected error sometimes it's difficult to decide whether I did something wrong or it's a software bug.

Actually I'm not a user, I'm a programmer and I write a two-way interface between our CAD application and EPANET. This means that I must use the command line version of EPANET which seems to work fine now.

Thank you very much again. 

Best regards,

Peter
