### ISSUE TITLE
request additional api function for getting finer-grained time step information

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#681]
in my application, I have a need to know when the next time step boundary will occur, and for what reason. Epanet tracks this internally, but it mutates some internal data when doing so. proper implementation would not mutate the data structure but just return the time horizon for informational purposes.

possible reasons for time stepping are:

- report time step boundary
- hydraulic time step boundary
- water quality time step boundary
- tank fill/empty event
- rule- or control- based event (time/level)

**Comment by lbutler** [comment]
This would be a great addition, potentially including this information as an output into the full report would be beneficial for users of the GUI.

Early in the calibration of a model, if something isn't set correctly, the first way you know is because of excess timesteps, and currently you need to go through each asset to find out what's causing it (typically a full or empty tank)
