### ISSUE TITLE
What Happened to the Continuous Integration Tests

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#703]
For a PR submitted earlier today I noticed that the Appveyor CI tests were no longer being made as they have in the past. Is this a result of the changes made to the GitHub workflow actions (as in PR #701) and was it intentional? Although I was never a big fan of the closeness tests made to results for the 47 benchmark networks, I did think that the unit tests of new features using the Boost Auto-Test  framework (for the files in the project's tests folder) were useful.

**Comment by eladsal** [comment]
Definitely not intentional. The `build` badge on the repo main page points to this log:
https://ci.appveyor.com/project/OpenWaterAnalytics/epanet
"Error fetching YAML configuration file from the repository. Make sure AppVeyor is authorized to access your gitHub account: GitHub authorization required."

I don't know how to fix this. @samhatchett @Mariosmsk ?

**Comment by eladsal** [comment]
@LRossman, all the checks on your PR #702 are good now.
