### ISSUE TITLE
What is the license for this version of EPANET?

### ISSUE THREAD

**Issue by goanpeca** [OpenWaterAnalytics/EPANET#79]
Most (if not all?) OS projects have a LICENSE or LICENSE.txt (to be friendly to win users) on the main repository.

**Comment by samhatchett** [comment]
touchy subject, but an important point. original EPANET is public-domain, the community version is probably MIT or similar. We need to finalize this and post the LICENSE

**Comment by goanpeca** [comment]
@samhatchett, sure BSD or MIT should both work, I guess (I am partial to MIT, but it is more a thing of tradition than nothing else)?

Thanks for the reply

**Comment by samhatchett** [comment]
For anyone tuned into this issue... After too much deliberation among the organizers, I've put up the MIT license on the repo. If any contributor has "non-trivial" code in the mix, and if you don't agree to license your code under these terms, please let me know as soon as possible. 

Perhaps I posted the license too soon, without explicit acknowledgement from each and every contributor. But my reasoning was that since the original code was Public Domain (US Gov't code), I didn't think that the MIT license would be an unreasonable burden, nor grant unexpected freedoms to users of the code. We've just been sitting on this issue for so long that something needed to be done.

**Comment by eladsal** [comment]
The license is MIT. Time to close the issue and move on... thanks all.
