### ISSUE TITLE
Consider gitter.im as an alternative for live comms?

### ISSUE THREAD

**Issue by goanpeca** [OpenWaterAnalytics/EPANET#80]
I know there is a forum for discussion, but it is not very pretty nor inviting. Have you considered using something like http://gitter.im/ ?

**Comment by samhatchett** [comment]
Do you have specific criticisms about the forum software? Discourse is widely used.

**Comment by goanpeca** [comment]
- I would say It is not efficient to have async conversations
- Its nice to have a place to have live discussion of stuff.
- Gitter allows pretty formatting of code (python, C, etc...)
- Gitter integrates with github, so for github users is seamless
- It looks like "old technology" and not very pretty, so new users might not be so eager to jump in that workflow

- Anyway I am more in favor of using newer channels for outreach not on closing the forum. I guess some people feel comfortable with that tool.

**Comment by michaeltryby** [comment]
I don't know @samhatchett Gitter does look pretty cool :smile:

**Comment by eldemet** [comment]
1. Changing the discussion platform can have a significant cost.
2. The Forum is already active (there are already more than 120 registered users) and there is already a lot of information piling up.
3. There will always be another solution which is better than the existing one (e.g why don't move everything to [Slack](https://slack.com/) ). 

If there is a way to export the data and users, in order to import them to a different platform at some point in the future, this would be nice idea. However for now, I believe we should keep the forum as it is.

**Comment by samhatchett** [comment]
The EPANET-dev committee is using Slack for real-time chat currently. We can talk about opening our Slack team to more interested developers, but the arguments against the existing forum sound like matters of taste more than functional concerns. The async vs RTC divide is difficult too because I personally favor async; i'm busy and we all live in different time zones. 

@goanpeca if there is something that you want to accomplish through RTC or if there is something that only Gitter provides, then let's discuss that rather than attempting to denigrate the hard work we've done in building the community through the forums.

**Comment by goanpeca** [comment]
Slack is fine, if you already use it ;-)

**Comment by samhatchett** [comment]
I would be shocked if this project's lack of engagement was due to lack of channels for communication. But I am definitely `+1` for experimentation. @goanpeca if you would like to run a Gitter for the epanet development community, please feel free to give it a shot and announce it on the forums.
