### ISSUE TITLE
Declaration of idstodelete in ENdeletenode

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#96]
In [ENdeletenode](https://github.com/OpenWaterAnalytics/EPANET/blob/dev-net-builder/src/epanet.c#L3579) [idstodeleteis](https://github.com/OpenWaterAnalytics/EPANET/blob/dev-net-builder/src/epanet.c#L3583) declared as:
`char *idstodelete[20][32];`

This causes some compilation warnings as this array is not compatible with `strcpy` and with `ENgetlinkindex` at line [3629](https://github.com/OpenWaterAnalytics/EPANET/blob/dev-net-builder/src/epanet.c#L3629).

I wonder if we could go with `char *idstodelete[20];`?

**Comment by AbelHeinsbroek** [comment]
Yes that should be possible, but my C knowledge is still basic at best, so I didn't found a better way to implement it yet. Likewise, the semi-randomly chosen limit of 20 should be removed as well.

**Comment by samhatchett** [comment]
Instead of tracking ids, I think we can just directly delete links in reverse-index order, right?

**Comment by AbelHeinsbroek** [comment]
No that does not work! Because deleting links changes the links array we risk skipping over one!

For example, say we have node 'a' with links 'l1' with index 4 and 'l2' with index 5. If we delete link 'l1', the index of 'l2' becomes 4, which we'll skip by incrementing i, which becomes 5..

A simpler solution might be simply decrement variable i with 1. That should work as well I guess?

**Comment by samhatchett** [comment]
my suggestion was (to use your example): 
first delete 'l2'(idx 5), then delete 'l1'(idx 4). maybe that is what you are also saying?
this line does what I describe: https://github.com/OpenWaterAnalytics/EPANET/commit/df00b49ea03801a1e5fc50b2ce38e425ac57afdc#diff-38a911bd86983e691fa46711d21ba3b6R3642

**Comment by AbelHeinsbroek** [comment]
My bad, I missed the reversed-index-order part of your commit. This should work as well of course.
